Idenguefy: Idenguefy.Controllers.AlertManager Class Reference
Idenguefy.Controllers.AlertManager Class Reference
Manages all alert-related functionalities, including evaluating dengue clusters, monitoring user and pointer locations, saving alerts, and notifying subscribers.
Public Member Functions
void RegisterSubscriber (IAlertSubscriber sub)
Registers a subscriber to receive alert notifications.
void UnregisterSubscriber (IAlertSubscriber sub)
Unregisters a subscriber from receiving alert notifications.
void EvaluateAlerts ()
Evaluates all active clusters and triggers alerts based on user location and map pointers.
List< Alert > GetSavedAlerts ()
Retrieves a copy of all saved alerts.
void ClearSavedAlerts ()
Clears all saved alerts from memory and persistent storage.
Public Attributes
ClusterController clusterController
Reference to the ClusterController managing dengue clusters.
LiveLocationController locationController
Reference to the LiveLocationController tracking the user's location.
float evalInterval = 10f
Time interval (in seconds) between each background evaluation.
double durationThreshold = 60.0
Minimum duration (in seconds) before a repeated alert can be triggered for the same source.
Properties
static AlertManager Instance [get, private set]
Singleton instance of the AlertManager.
Private Member Functions
void Awake ()
Initializes the singleton instance and ensures persistence between scenes.
void Start ()
Called on start.
IEnumerator BackgroundEvaluator ()
Periodically evaluates nearby dengue clusters relative to pointers and user location.
void LoadSavedAlerts ()
Loads saved alerts from persistent storage.
void NotifySubscribers (AlertData data)
Notifies all registered subscribers about a triggered alert.
void SaveAlert (AlertData data)
Saves the given alert data to memory and persistent storage.
Private Attributes
List< IAlertSubscriber > subscribers = new()
List of subscribers that are notified when alerts are triggered.
List< Alert > savedAlerts = new List<Alert>()
List storing all saved alert instances.
DataManager< Alert > alertDataManager = new DataManager<Alert>("Idenguefy_Alerts")
Handles saving and loading alert data persistently.
Coroutine backgroundCheckCoroutine
Coroutine responsible for continuously evaluating alerts at set intervals.
readonly Dictionary< string, DateTime > lastNotifyTimes = new()
Tracks the last time an alert was triggered for each pointer or user location.
Detailed Description
Manages all alert-related functionalities, including evaluating dengue clusters, monitoring user and pointer locations, saving alerts, and notifying subscribers.
Definition at line 31 of file AlertManager.cs.
Member Function Documentation
Awake()
void Idenguefy.Controllers.AlertManager.Awake () private
Initializes the singleton instance and ensures persistence between scenes.
Definition at line 88 of file AlertManager.cs.
References Instance.
BackgroundEvaluator()
IEnumerator Idenguefy.Controllers.AlertManager.BackgroundEvaluator () private
Periodically evaluates nearby dengue clusters relative to pointers and user location.
Definition at line 112 of file AlertManager.cs.
References evalInterval, and EvaluateAlerts().
Referenced by Start().
ClearSavedAlerts()
void Idenguefy.Controllers.AlertManager.ClearSavedAlerts ()
Clears all saved alerts from memory and persistent storage.
Definition at line 324 of file AlertManager.cs.
References alertDataManager, and savedAlerts.
Referenced by Idenguefy.Boundaries.AlertHistoryView.ClearAllAlerts().
EvaluateAlerts()
void Idenguefy.Controllers.AlertManager.EvaluateAlerts ()
Evaluates all active clusters and triggers alerts based on user location and map pointers.
Definition at line 153 of file AlertManager.cs.
References clusterController, durationThreshold, Idenguefy.Controllers.SettingsController.GetThresholdPref(), Idenguefy.Controllers.MapUtils.HaversineDistance(), Idenguefy.Entities.Indoor, lastNotifyTimes, Idenguefy.Controllers.PointerController.ListPointers(), locationController, NotifySubscribers(), and Idenguefy.Entities.Outdoor.
Referenced by Idenguefy.Developer.Developer.AlertTest(), and BackgroundEvaluator().
GetSavedAlerts()
List< Alert > Idenguefy.Controllers.AlertManager.GetSavedAlerts ()
Retrieves a copy of all saved alerts.
Returns
A list of all saved alerts.
Definition at line 307 of file AlertManager.cs.
References alertDataManager, and savedAlerts.
Referenced by Idenguefy.Boundaries.AlertHistoryView.RefreshAlertList().
LoadSavedAlerts()
void Idenguefy.Controllers.AlertManager.LoadSavedAlerts () private
Loads saved alerts from persistent storage.
Definition at line 124 of file AlertManager.cs.
References alertDataManager, and savedAlerts.
Referenced by Start().
NotifySubscribers()
void Idenguefy.Controllers.AlertManager.NotifySubscribers (AlertData data) private
Notifies all registered subscribers about a triggered alert.
Parameters
data The alert data to broadcast to subscribers.
Definition at line 276 of file AlertManager.cs.
References SaveAlert(), and subscribers.
Referenced by EvaluateAlerts().
RegisterSubscriber()
void Idenguefy.Controllers.AlertManager.RegisterSubscriber (IAlertSubscriber sub)
Registers a subscriber to receive alert notifications.
Parameters
sub The subscriber to be added.
Definition at line 134 of file AlertManager.cs.
References subscribers.
Referenced by Idenguefy.Boundaries.AlertHistoryView.EnsureRegistered(), Idenguefy.Boundaries.InAppAlertService.EnsureRegistered(), and Idenguefy.Boundaries.PhoneAlertService.Start().
SaveAlert()
void Idenguefy.Controllers.AlertManager.SaveAlert (AlertData data) private
Saves the given alert data to memory and persistent storage.
Parameters
data The alert data to be saved.
Definition at line 288 of file AlertManager.cs.
References alertDataManager, Idenguefy.Controllers.AlertData.Message, savedAlerts, Idenguefy.Controllers.AlertData.Timestamp, Idenguefy.Controllers.AlertData.Title, and Idenguefy.Controllers.AlertData.Type.
Referenced by NotifySubscribers().
Start()
void Idenguefy.Controllers.AlertManager.Start () private
Called on start.
Loads saved alerts and begins periodic background evaluation.
Definition at line 102 of file AlertManager.cs.
References backgroundCheckCoroutine, BackgroundEvaluator(), and LoadSavedAlerts().
UnregisterSubscriber()
void Idenguefy.Controllers.AlertManager.UnregisterSubscriber (IAlertSubscriber sub)
Unregisters a subscriber from receiving alert notifications.
Parameters
sub The subscriber to be removed.
Definition at line 144 of file AlertManager.cs.
References subscribers.
Referenced by Idenguefy.Boundaries.InAppAlertService.OnDisable().
Member Data Documentation
alertDataManager
DataManager<Alert> Idenguefy.Controllers.AlertManager.alertDataManager = new DataManager<Alert>("Idenguefy_Alerts") private
Handles saving and loading alert data persistently.
Definition at line 62 of file AlertManager.cs.
Referenced by ClearSavedAlerts(), GetSavedAlerts(), LoadSavedAlerts(), and SaveAlert().
backgroundCheckCoroutine
Coroutine Idenguefy.Controllers.AlertManager.backgroundCheckCoroutine private
Coroutine responsible for continuously evaluating alerts at set intervals.
Definition at line 68 of file AlertManager.cs.
Referenced by Start().
clusterController
ClusterController Idenguefy.Controllers.AlertManager.clusterController
Reference to the ClusterController managing dengue clusters.
Definition at line 46 of file AlertManager.cs.
Referenced by EvaluateAlerts().
durationThreshold
double Idenguefy.Controllers.AlertManager.durationThreshold = 60.0
Minimum duration (in seconds) before a repeated alert can be triggered for the same source.
Definition at line 83 of file AlertManager.cs.
Referenced by EvaluateAlerts().
evalInterval
float Idenguefy.Controllers.AlertManager.evalInterval = 10f
Time interval (in seconds) between each background evaluation.
Definition at line 73 of file AlertManager.cs.
Referenced by BackgroundEvaluator().
lastNotifyTimes
readonly Dictionary<string, DateTime> Idenguefy.Controllers.AlertManager.lastNotifyTimes = new() private
Tracks the last time an alert was triggered for each pointer or user location.
Definition at line 78 of file AlertManager.cs.
Referenced by EvaluateAlerts().
locationController
LiveLocationController Idenguefy.Controllers.AlertManager.locationController
Reference to the LiveLocationController tracking the user's location.
Definition at line 51 of file AlertManager.cs.
Referenced by EvaluateAlerts().
savedAlerts
List<Alert> Idenguefy.Controllers.AlertManager.savedAlerts = new List<Alert>() private
List storing all saved alert instances.
Definition at line 57 of file AlertManager.cs.
Referenced by ClearSavedAlerts(), GetSavedAlerts(), LoadSavedAlerts(), and SaveAlert().
subscribers
List<IAlertSubscriber> Idenguefy.Controllers.AlertManager.subscribers = new() private
List of subscribers that are notified when alerts are triggered.
Definition at line 41 of file AlertManager.cs.
Referenced by NotifySubscribers(), RegisterSubscriber(), and UnregisterSubscriber().
Property Documentation
Instance
AlertManager Idenguefy.Controllers.AlertManager.Instance static get private set
Singleton instance of the AlertManager.
Definition at line 36 of file AlertManager.cs.
Referenced by Idenguefy.Developer.Developer.AlertTest(), Awake(), Idenguefy.Boundaries.AlertHistoryView.ClearAllAlerts(), Idenguefy.Boundaries.AlertHistoryView.EnsureRegistered(), Idenguefy.Boundaries.InAppAlertService.EnsureRegistered(), Idenguefy.Boundaries.InAppAlertService.OnDisable(), Idenguefy.Boundaries.AlertHistoryView.RefreshAlertList(), and Idenguefy.Boundaries.PhoneAlertService.Start().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/AlertManager.cs