Idenguefy: Idenguefy.Controllers.SettingsController Class Reference
Idenguefy.Controllers.SettingsController Class Reference
Handles all interactions with the Settings entity.
Public Member Functions
SettingsController ()
Initializes a new instance of the SettingsController and loads existing settings from storage.
int GetThresholdPref ()
Gets the current proximity threshold preference.
void SetThresholdPref (int value)
Sets and saves the proximity threshold preference.
bool GetThemePref ()
Gets the current theme preference (Dark Mode on/off).
void SetThemePref (bool isDarkMode)
Sets and saves the theme preference.
string GetLangPref ()
Gets the current language preference.
void SetLangPref (string langCode)
Sets and saves the language preference.
void ResetSettings ()
Resets all settings to their default values and saves them.
Private Member Functions
void SaveSettings ()
Saves the current settings object to persistent storage using the DataManager.
void LoadSettings ()
Loads the settings object from persistent storage.
Private Attributes
Settings settings
The private Settings object instance currently holding the application's preferences.
DataManager< Settings > dataManager
The generic data manager responsible for serializing/deserializing the settings object.
Detailed Description
Handles all interactions with the Settings entity.
Manages loading, saving, and providing access to user preferences like theme, language, and proximity threshold.
Author: Sharina Version: 1.0
Definition at line 16 of file SettingsController.cs.
Constructor & Destructor Documentation
SettingsController()
Idenguefy.Controllers.SettingsController.SettingsController ()
Initializes a new instance of the SettingsController and loads existing settings from storage.
Definition at line 32 of file SettingsController.cs.
References dataManager, and LoadSettings().
Member Function Documentation
GetLangPref()
string Idenguefy.Controllers.SettingsController.GetLangPref ()
Gets the current language preference.
Returns
The language identifier string.
Definition at line 92 of file SettingsController.cs.
References settings.
Referenced by Idenguefy.Controllers.LocalizationManager.Awake(), and Idenguefy.Controllers.LocalizationManager.ToggleLanguage().
GetThemePref()
bool Idenguefy.Controllers.SettingsController.GetThemePref ()
Gets the current theme preference (Dark Mode on/off).
Returns
True if Dark Mode is enabled, false otherwise.
Definition at line 69 of file SettingsController.cs.
References settings.
Referenced by Idenguefy.Boundaries.PointerRenderer.CreatePointerMarker(), Idenguefy.Boundaries.ThemeApplier.OnToggleTheme(), and Idenguefy.Boundaries.PointerRenderer.RecolorPointers().
GetThresholdPref()
int Idenguefy.Controllers.SettingsController.GetThresholdPref ()
Gets the current proximity threshold preference.
Returns
The proximity threshold value.
Definition at line 46 of file SettingsController.cs.
References settings.
Referenced by Idenguefy.Controllers.AlertManager.EvaluateAlerts().
LoadSettings()
void Idenguefy.Controllers.SettingsController.LoadSettings () private
Loads the settings object from persistent storage.
If no settings are found, it initializes with default values.
Definition at line 128 of file SettingsController.cs.
References dataManager, and settings.
Referenced by SettingsController().
ResetSettings()
void Idenguefy.Controllers.SettingsController.ResetSettings ()
Resets all settings to their default values and saves them.
Definition at line 150 of file SettingsController.cs.
References SaveSettings(), and settings.
SaveSettings()
void Idenguefy.Controllers.SettingsController.SaveSettings () private
Saves the current settings object to persistent storage using the DataManager.
Definition at line 114 of file SettingsController.cs.
References dataManager, and settings.
Referenced by ResetSettings(), SetLangPref(), SetThemePref(), and SetThresholdPref().
SetLangPref()
void Idenguefy.Controllers.SettingsController.SetLangPref (string langCode)
Sets and saves the language preference.
Parameters
langCode The new language identifier string.
Definition at line 101 of file SettingsController.cs.
References SaveSettings().
SetThemePref()
void Idenguefy.Controllers.SettingsController.SetThemePref (bool isDarkMode)
Sets and saves the theme preference.
Parameters
isDarkMode The new theme state (true for Dark Mode).
Definition at line 78 of file SettingsController.cs.
References SaveSettings().
SetThresholdPref()
void Idenguefy.Controllers.SettingsController.SetThresholdPref (int value)
Sets and saves the proximity threshold preference.
Parameters
value The new threshold value.
Definition at line 55 of file SettingsController.cs.
References SaveSettings().
Member Data Documentation
dataManager
DataManager<Settings> Idenguefy.Controllers.SettingsController.dataManager private
The generic data manager responsible for serializing/deserializing the settings object.
Definition at line 26 of file SettingsController.cs.
Referenced by LoadSettings(), SaveSettings(), and SettingsController().
settings
Settings Idenguefy.Controllers.SettingsController.settings private
The private Settings object instance currently holding the application's preferences.
Definition at line 21 of file SettingsController.cs.
Referenced by GetLangPref(), GetThemePref(), GetThresholdPref(), LoadSettings(), ResetSettings(), and SaveSettings().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/SettingsController.cs