Idenguefy: Idenguefy.Boundaries.AlertHistoryView Class Reference
Idenguefy.Boundaries.AlertHistoryView Class Reference
Displays a scrollable list of saved alerts (from AlertManager).
Public Member Functions
void RefreshAlertList ()
Clears current UI and rebuilds it from the AlertManager’s saved list.
void ClearAllAlerts ()
Clears all saved alerts from memory and storage.
void OnAlertTriggered (AlertData data)
Allows this instance of the subscriber to perform actions upon an alert triggering.
Public Attributes
RectTransform alertContainer
GameObject alertItemPrefab
GameObject emptyStateText
Private Member Functions
void Start ()
System.Collections.IEnumerator EnsureRegistered ()
Sets up and ensures AlertHistoryView Class is subscribed to and observes the AlertManager Class via an IEnumerator.
Private Attributes
List< GameObject > activeAlertItems = new()
Detailed Description
Displays a scrollable list of saved alerts (from AlertManager).
Responsibilities:
Fetch saved alerts from AlertManager
Instantiate alert UI prefabs dynamically
Allow users to clear all alerts if desired
Author: Xavier Version: 1.0
Definition at line 26 of file AlertHistoryView.cs.
Member Function Documentation
ClearAllAlerts()
void Idenguefy.Boundaries.AlertHistoryView.ClearAllAlerts ()
Clears all saved alerts from memory and storage.
Definition at line 113 of file AlertHistoryView.cs.
References Idenguefy.Controllers.AlertManager.ClearSavedAlerts(), Idenguefy.Controllers.AlertManager.Instance, and RefreshAlertList().
EnsureRegistered()
System.Collections.IEnumerator Idenguefy.Boundaries.AlertHistoryView.EnsureRegistered () private
Sets up and ensures AlertHistoryView Class is subscribed to and observes the AlertManager Class via an IEnumerator.
Returns
Definition at line 45 of file AlertHistoryView.cs.
References Idenguefy.Controllers.AlertManager.Instance, and Idenguefy.Controllers.AlertManager.RegisterSubscriber().
Referenced by Start().
OnAlertTriggered()
void Idenguefy.Boundaries.AlertHistoryView.OnAlertTriggered (AlertData data)
Allows this instance of the subscriber to perform actions upon an alert triggering.
Parameters
data
Implements Idenguefy.Controllers.IAlertSubscriber.
Definition at line 126 of file AlertHistoryView.cs.
References RefreshAlertList().
RefreshAlertList()
void Idenguefy.Boundaries.AlertHistoryView.RefreshAlertList ()
Clears current UI and rebuilds it from the AlertManager’s saved list.
Definition at line 56 of file AlertHistoryView.cs.
References activeAlertItems, alertContainer, alertItemPrefab, emptyStateText, Idenguefy.Controllers.AlertManager.GetSavedAlerts(), Idenguefy.Controllers.AlertManager.Instance, Idenguefy.Entities.Alert.Message, Idenguefy.Entities.Alert.Timestamp, Idenguefy.Entities.Alert.Title, and Idenguefy.Entities.Alert.Type.
Referenced by ClearAllAlerts(), OnAlertTriggered(), and Start().
Start()
void Idenguefy.Boundaries.AlertHistoryView.Start () private
Definition at line 35 of file AlertHistoryView.cs.
References EnsureRegistered(), and RefreshAlertList().
Member Data Documentation
activeAlertItems
List<GameObject> Idenguefy.Boundaries.AlertHistoryView.activeAlertItems = new() private
Definition at line 33 of file AlertHistoryView.cs.
Referenced by RefreshAlertList().
alertContainer
RectTransform Idenguefy.Boundaries.AlertHistoryView.alertContainer
Definition at line 29 of file AlertHistoryView.cs.
Referenced by RefreshAlertList().
alertItemPrefab
GameObject Idenguefy.Boundaries.AlertHistoryView.alertItemPrefab
Definition at line 30 of file AlertHistoryView.cs.
Referenced by RefreshAlertList().
emptyStateText
GameObject Idenguefy.Boundaries.AlertHistoryView.emptyStateText
Definition at line 31 of file AlertHistoryView.cs.
Referenced by RefreshAlertList().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/AlertHistoryView.cs