Idenguefy: Idenguefy.Boundaries.ThemeApplier Class Reference
Idenguefy.Boundaries.ThemeApplier Class Reference
Used to update all applicable objects colour depending on the users selected colour theme.
Public Types
enum ThemeMode { Light , Dark }
Defines the two possible theme states.
Public Member Functions
void ApplyTheme (ThemeData theme)
Applies the selected colour theme data to all applicable UI elements.
void OnToggleTheme ()
Called by UI elements (like SettingsView) to signal a theme toggle.
void AutoPopulateAllUIElementsInScene ()
Auto-populates all UI element lists from the entire scene using Object.FindObjectsByType.
Private Member Functions
void Start ()
On Start, finds all UI elements, caches sprites, and applies the initial theme.
void OnEnable ()
Registers this applier with the ThemeManager when enabled.
void OnDisable ()
Unregisters this applier from the ThemeManager when disabled.
void ApplyTheme (ThemeMode theme)
Applies the selected theme for Sprites (UI Images and SpriteRenderers).
void CacheAllSprites ()
Caches all Sprites from all "Resources" folders to prepare for swapping.
Sprite GetSwappedSprite (Sprite currentSprite, ThemeMode targetTheme)
Finds the theme-appropriate version of a sprite based on its name.
ThemeData GetThemeDataFromMode (ThemeMode mode)
Retrieves the theme data (colors) from the ThemeManager based on the mode.
Private Attributes
ThemeMode currentTheme = ThemeMode.Light
List< Image > allImages = new List<Image>()
List< SpriteRenderer > allSpriteRenderers = new List<SpriteRenderer>()
readonly Dictionary< string, Sprite > spriteCache = new Dictionary<string, Sprite>()
A cache of sprites loaded from the Resources folder for fast swapping.
List< Image > imageTargets = new List<Image>()
List< Button > buttonTargets = new List<Button>()
List< TMP_Text > textTargets = new List<TMP_Text>()
List< TMP_InputField > inputFieldTargets = new List<TMP_InputField>()
List< Toggle > toggleTargets = new List<Toggle>()
List< Slider > sliderTargets = new List<Slider>()
List< TMP_Dropdown > dropdownTargets = new List<TMP_Dropdown>()
Detailed Description
Used to update all applicable objects colour depending on the users selected colour theme.
This component finds all UI elements in the scene and applies theme colors. It also swaps sprites based on a "Light Mode" / "Dark Mode" naming convention.
Author: Napatr Version: 1.0
Definition at line 21 of file ThemeApplier.cs.
Member Enumeration Documentation
ThemeMode
enum Idenguefy.Boundaries.ThemeApplier.ThemeMode
Defines the two possible theme states.
Enumerator
Light
Dark
Definition at line 26 of file ThemeApplier.cs.
Member Function Documentation
ApplyTheme() [1/2]
void Idenguefy.Boundaries.ThemeApplier.ApplyTheme (ThemeData theme)
Applies the selected colour theme data to all applicable UI elements.
Parameters
theme The ThemeData object containing the colors to apply.
Definition at line 94 of file ThemeApplier.cs.
References buttonTargets, dropdownTargets, imageTargets, inputFieldTargets, sliderTargets, textTargets, and toggleTargets.
Referenced by OnToggleTheme(), Idenguefy.Controllers.ThemeManager.Register(), and Start().
ApplyTheme() [2/2]
void Idenguefy.Boundaries.ThemeApplier.ApplyTheme (ThemeMode theme) private
Applies the selected theme for Sprites (UI Images and SpriteRenderers).
Parameters
theme The target theme mode (Light or Dark).
Definition at line 256 of file ThemeApplier.cs.
References allImages, allSpriteRenderers, and GetSwappedSprite().
AutoPopulateAllUIElementsInScene()
void Idenguefy.Boundaries.ThemeApplier.AutoPopulateAllUIElementsInScene ()
Auto-populates all UI element lists from the entire scene using Object.FindObjectsByType.
Definition at line 228 of file ThemeApplier.cs.
References allImages, allSpriteRenderers, buttonTargets, dropdownTargets, imageTargets, inputFieldTargets, sliderTargets, textTargets, and toggleTargets.
Referenced by Start().
CacheAllSprites()
void Idenguefy.Boundaries.ThemeApplier.CacheAllSprites () private
Caches all Sprites from all "Resources" folders to prepare for swapping.
Definition at line 291 of file ThemeApplier.cs.
References spriteCache.
Referenced by Start().
GetSwappedSprite()
Sprite Idenguefy.Boundaries.ThemeApplier.GetSwappedSprite (Sprite currentSprite, ThemeMode targetTheme) private
Finds the theme-appropriate version of a sprite based on its name.
(e.g., "icon_Light Mode" -> "icon_Dark Mode").
Parameters
currentSprite The sprite currently in use.
targetTheme The theme to swap to.
Returns
The swapped sprite if found in the cache, otherwise null.
Definition at line 314 of file ThemeApplier.cs.
References spriteCache.
Referenced by ApplyTheme().
GetThemeDataFromMode()
ThemeData Idenguefy.Boundaries.ThemeApplier.GetThemeDataFromMode (ThemeMode mode) private
Retrieves the theme data (colors) from the ThemeManager based on the mode.
Parameters
mode The theme mode (Light or Dark).
Returns
The corresponding ThemeData object, or null if the manager isn't found.
Definition at line 350 of file ThemeApplier.cs.
References Idenguefy.Controllers.ThemeManager.Instance, and Idenguefy.Controllers.ThemeManager.lightTheme.
Referenced by OnToggleTheme(), and Start().
OnDisable()
void Idenguefy.Boundaries.ThemeApplier.OnDisable () private
Unregisters this applier from the ThemeManager when disabled.
Definition at line 84 of file ThemeApplier.cs.
References Idenguefy.Controllers.ThemeManager.Instance, and Idenguefy.Controllers.ThemeManager.Unregister().
OnEnable()
void Idenguefy.Boundaries.ThemeApplier.OnEnable () private
Registers this applier with the ThemeManager when enabled.
Definition at line 75 of file ThemeApplier.cs.
References Idenguefy.Controllers.ThemeManager.Instance, and Idenguefy.Controllers.ThemeManager.Register().
OnToggleTheme()
void Idenguefy.Boundaries.ThemeApplier.OnToggleTheme ()
Called by UI elements (like SettingsView) to signal a theme toggle.
This fetches the new theme, applies colors, and applies sprite swaps.
Definition at line 210 of file ThemeApplier.cs.
References ApplyTheme(), currentTheme, Dark, GetThemeDataFromMode(), Idenguefy.Controllers.SettingsController.GetThemePref(), Idenguefy.Controllers.ThemeManager.Instance, and Idenguefy.Controllers.ThemeManager.ToggleTheme().
Start()
void Idenguefy.Boundaries.ThemeApplier.Start () private
On Start, finds all UI elements, caches sprites, and applies the initial theme.
Definition at line 62 of file ThemeApplier.cs.
References ApplyTheme(), AutoPopulateAllUIElementsInScene(), CacheAllSprites(), currentTheme, and GetThemeDataFromMode().
Member Data Documentation
allImages
List<Image> Idenguefy.Boundaries.ThemeApplier.allImages = new List<Image>() private
Definition at line 34 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
allSpriteRenderers
List<SpriteRenderer> Idenguefy.Boundaries.ThemeApplier.allSpriteRenderers = new List<SpriteRenderer>() private
Definition at line 36 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
buttonTargets
List<Button> Idenguefy.Boundaries.ThemeApplier.buttonTargets = new List<Button>() private
Definition at line 47 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
currentTheme
ThemeMode Idenguefy.Boundaries.ThemeApplier.currentTheme = ThemeMode.Light private
Definition at line 30 of file ThemeApplier.cs.
Referenced by OnToggleTheme(), and Start().
dropdownTargets
List<TMP_Dropdown> Idenguefy.Boundaries.ThemeApplier.dropdownTargets = new List<TMP_Dropdown>() private
Definition at line 57 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
imageTargets
List<Image> Idenguefy.Boundaries.ThemeApplier.imageTargets = new List<Image>() private
Definition at line 45 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
inputFieldTargets
List<TMP_InputField> Idenguefy.Boundaries.ThemeApplier.inputFieldTargets = new List<TMP_InputField>() private
Definition at line 51 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
sliderTargets
List<Slider> Idenguefy.Boundaries.ThemeApplier.sliderTargets = new List<Slider>() private
Definition at line 55 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
spriteCache
readonly Dictionary<string, Sprite> Idenguefy.Boundaries.ThemeApplier.spriteCache = new Dictionary<string, Sprite>() private
A cache of sprites loaded from the Resources folder for fast swapping.
Definition at line 41 of file ThemeApplier.cs.
Referenced by CacheAllSprites(), and GetSwappedSprite().
textTargets
List<TMP_Text> Idenguefy.Boundaries.ThemeApplier.textTargets = new List<TMP_Text>() private
Definition at line 49 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
toggleTargets
List<Toggle> Idenguefy.Boundaries.ThemeApplier.toggleTargets = new List<Toggle>() private
Definition at line 53 of file ThemeApplier.cs.
Referenced by ApplyTheme(), and AutoPopulateAllUIElementsInScene().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/ThemeApplier.cs