Idenguefy: Idenguefy.Controllers.NEA_Cluster_API_Handler Class Reference
Idenguefy.Controllers.NEA_Cluster_API_Handler Class Reference
An implementation of Cluster_API_Handler that fetches dengue cluster data specifically from the Singapore NEA dataset via data.gov.sg.
Classes
class ApiResponse
A serializable class to map the JSON response from the initial API poll.
class ApiData
A nested serializable class representing the "data" object in the ApiResponse.
Public Member Functions
override IEnumerator FetchClusterData ()
Overrides the base method to fetch cluster data from the data.gov.sg API.
Public Member Functions inherited from Idenguefy.Controllers.Cluster_API_Handler
IEnumerator FetchClusterData ()
When implemented in a derived class, begins fetching cluster data from the specific API.
Protected Member Functions
override void PreprocessData (string datasetJson)
Parses the raw GeoJSON string from the NEA dataset into the Clusters list.
Protected Member Functions inherited from Idenguefy.Controllers.Cluster_API_Handler
void PreprocessData (string datasetJson)
When implemented in a derived class, converts a raw JSON string into the Clusters list.
virtual string DetermineSeverity (int caseSize)
A virtual helper method to determine a cluster's severity based on its case size.
Private Attributes
readonly string datasetId = "d_dbfabf16158d1b0e1c420627c0819168"
The specific dataset ID for the NEA Dengue Clusters on data.gov.sg.
readonly string baseUrl = "https://api-open.data.gov.sg/v1/public/api/datasets/"
The base URL for the data.gov.sg public API.
Additional Inherited Members
Properties inherited from Idenguefy.Controllers.Cluster_API_Handler
List< DengueCluster > Clusters = new List<DengueCluster>() [get, protected set]
Gets the list of DengueCluster objects that have been parsed by the handler.
Detailed Description
An implementation of Cluster_API_Handler that fetches dengue cluster data specifically from the Singapore NEA dataset via data.gov.sg.
This handler manages the two-step API call process:
Polls the main dataset API to get a temporary download URL.
Downloads the actual GeoJSON dataset from that URL.
Parses the GeoJSON into DengueCluster objects.
Author: Napatr Version: 1.0
Definition at line 24 of file NEA_Cluster_API_Handler.cs.
Member Function Documentation
FetchClusterData()
override IEnumerator Idenguefy.Controllers.NEA_Cluster_API_Handler.FetchClusterData ()
Overrides the base method to fetch cluster data from the data.gov.sg API.
Performs a two-step request as required by the API.
Returns
An IEnumerator for the coroutine execution.
Definition at line 40 of file NEA_Cluster_API_Handler.cs.
References baseUrl, Idenguefy.Controllers.NEA_Cluster_API_Handler.ApiResponse.code, Idenguefy.Controllers.NEA_Cluster_API_Handler.ApiResponse.data, datasetId, Idenguefy.Controllers.NEA_Cluster_API_Handler.ApiResponse.errMsg, PreprocessData(), and Idenguefy.Controllers.NEA_Cluster_API_Handler.ApiData.url.
PreprocessData()
override void Idenguefy.Controllers.NEA_Cluster_API_Handler.PreprocessData (string datasetJson) protected
Parses the raw GeoJSON string from the NEA dataset into the Clusters list.
Parameters
datasetJson The raw GeoJSON data as a string.
Definition at line 85 of file NEA_Cluster_API_Handler.cs.
References Idenguefy.Controllers.Cluster_API_Handler.Clusters, and Idenguefy.Controllers.Cluster_API_Handler.DetermineSeverity().
Referenced by FetchClusterData().
Member Data Documentation
baseUrl
readonly string Idenguefy.Controllers.NEA_Cluster_API_Handler.baseUrl = "https://api-open.data.gov.sg/v1/public/api/datasets/" private
The base URL for the data.gov.sg public API.
Definition at line 33 of file NEA_Cluster_API_Handler.cs.
Referenced by FetchClusterData().
datasetId
readonly string Idenguefy.Controllers.NEA_Cluster_API_Handler.datasetId = "d_dbfabf16158d1b0e1c420627c0819168" private
The specific dataset ID for the NEA Dengue Clusters on data.gov.sg.
Definition at line 29 of file NEA_Cluster_API_Handler.cs.
Referenced by FetchClusterData().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/API/NEA_Cluster_API_Handler.cs