Idenguefy: Idenguefy.Boundaries.ClusterView Class Reference
Idenguefy.Boundaries.ClusterView Class Reference
Contains all logic related to interacting with additional Cluster UI.
Public Member Functions
void ShowClusterList ()
Show the cluster list panel and refresh contents.
Public Attributes
ClusterController clusterController
RectTransform clusterEntryContainer
GameObject clusterEntryPrefab
GameObject emptyStateText
ClusterRenderer clusterRenderer
Private Member Functions
void OnEnable ()
When the component is enabled, automatically refresh the cluster list.
void RefreshClusterList ()
Clears old cluster entries and rebuilds from ClusterController data.
Private Attributes
readonly List< GameObject > clusterEntries = new()
A list of the currently instantiated cluster entry GameObjects in the view.
Detailed Description
Contains all logic related to interacting with additional Cluster UI.
Shows all Dengue Clusters on a popup screen
Author: Xavier Version: 1.0
Definition at line 20 of file ClusterView.cs.
Member Function Documentation
OnEnable()
void Idenguefy.Boundaries.ClusterView.OnEnable () private
When the component is enabled, automatically refresh the cluster list.
Definition at line 46 of file ClusterView.cs.
References RefreshClusterList().
RefreshClusterList()
void Idenguefy.Boundaries.ClusterView.RefreshClusterList () private
Clears old cluster entries and rebuilds from ClusterController data.
Definition at line 63 of file ClusterView.cs.
References clusterController, clusterEntries, clusterEntryContainer, clusterEntryPrefab, and emptyStateText.
Referenced by OnEnable(), and ShowClusterList().
ShowClusterList()
void Idenguefy.Boundaries.ClusterView.ShowClusterList ()
Show the cluster list panel and refresh contents.
Definition at line 54 of file ClusterView.cs.
References RefreshClusterList().
Member Data Documentation
clusterController
ClusterController Idenguefy.Boundaries.ClusterView.clusterController
Definition at line 24 of file ClusterView.cs.
Referenced by RefreshClusterList().
clusterEntries
readonly List<GameObject> Idenguefy.Boundaries.ClusterView.clusterEntries = new() private
A list of the currently instantiated cluster entry GameObjects in the view.
Definition at line 41 of file ClusterView.cs.
Referenced by RefreshClusterList().
clusterEntryContainer
RectTransform Idenguefy.Boundaries.ClusterView.clusterEntryContainer
Definition at line 28 of file ClusterView.cs.
Referenced by RefreshClusterList().
clusterEntryPrefab
GameObject Idenguefy.Boundaries.ClusterView.clusterEntryPrefab
Definition at line 30 of file ClusterView.cs.
Referenced by RefreshClusterList().
clusterRenderer
ClusterRenderer Idenguefy.Boundaries.ClusterView.clusterRenderer
Definition at line 36 of file ClusterView.cs.
emptyStateText
GameObject Idenguefy.Boundaries.ClusterView.emptyStateText
Definition at line 32 of file ClusterView.cs.
Referenced by RefreshClusterList().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/ClusterView.cs