Idenguefy: Idenguefy.Controllers.LiveLocationController Class Reference
Idenguefy.Controllers.LiveLocationController Class Reference
Manages live GPS location data for the Idenguefy application.
Public Member Functions
void UpdateLocation ()
Updates the current location data from Unity’s location service.
Public Attributes
float lon
The most recently retrieved coordinates of the device, represented as (longitude, latitude).
bool useMockLocationInEditor = true
Enables the use of mock coordinates when testing within the Unity Editor.
Vector2 mockCoordinates = new Vector2(103.6831f, 1.3483f)
The mock GPS coordinates (longitude, latitude) used for testing purposes in the Editor.
Properties
float float lat CurrentCoordinates [get, private set]
bool IsReady = false [get, private set]
Indicates whether the location service or mock data is ready for use.
Private Member Functions
IEnumerator Start ()
Coroutine that initializes the device’s location service and retrieves the initial coordinates.
Detailed Description
Manages live GPS location data for the Idenguefy application.
Responsibilities:
Retrieves the user’s real-time GPS coordinates using Unity’s location services.
Provides mock location support for testing within the Unity Editor.
Exposes a public interface to access the user’s current location and readiness state.
Author: Xavier Version: 1.0
This controller provides a single point of access for location-based data, ensuring that other systems (e.g., AlertManager, Map utilities) can safely query the user’s coordinates.
Definition at line 22 of file LiveLocationController.cs.
Member Function Documentation
Start()
IEnumerator Idenguefy.Controllers.LiveLocationController.Start () private
Coroutine that initializes the device’s location service and retrieves the initial coordinates.
Falls back to mock coordinates when location access is unavailable or disabled.
Returns
An IEnumerator coroutine for Unity’s location initialization sequence.
Definition at line 51 of file LiveLocationController.cs.
References CurrentCoordinates, IsReady, mockCoordinates, UpdateLocation(), and useMockLocationInEditor.
UpdateLocation()
void Idenguefy.Controllers.LiveLocationController.UpdateLocation ()
Updates the current location data from Unity’s location service.
This method should be called periodically to refresh coordinates.
Definition at line 97 of file LiveLocationController.cs.
References CurrentCoordinates, and IsReady.
Referenced by Start().
Member Data Documentation
lon
float Idenguefy.Controllers.LiveLocationController.lon
The most recently retrieved coordinates of the device, represented as (longitude, latitude).
Definition at line 27 of file LiveLocationController.cs.
mockCoordinates
Vector2 Idenguefy.Controllers.LiveLocationController.mockCoordinates = new Vector2(103.6831f, 1.3483f)
The mock GPS coordinates (longitude, latitude) used for testing purposes in the Editor.
Defaults to Singapore’s approximate central coordinates.
Definition at line 44 of file LiveLocationController.cs.
Referenced by Start().
useMockLocationInEditor
bool Idenguefy.Controllers.LiveLocationController.useMockLocationInEditor = true
Enables the use of mock coordinates when testing within the Unity Editor.
Definition at line 38 of file LiveLocationController.cs.
Referenced by Start().
Property Documentation
CurrentCoordinates
float float lat Idenguefy.Controllers.LiveLocationController.CurrentCoordinates get private set
Definition at line 27 of file LiveLocationController.cs.
Referenced by Start(), and UpdateLocation().
IsReady
bool Idenguefy.Controllers.LiveLocationController.IsReady = false get private set
Indicates whether the location service or mock data is ready for use.
Definition at line 32 of file LiveLocationController.cs.
Referenced by Start(), and UpdateLocation().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/LiveLocationController.cs