Idenguefy: Idenguefy.Boundaries.PointerRenderer Class Reference
Idenguefy.Boundaries.PointerRenderer Class Reference
Responsible for rendering the users saved map pointers onto the UI map.
Public Member Functions
void DrawAllPointers (List< MapPointer > pointers, int zoom, int xMin, int yMin, float tileSize)
Draws all pointers onto the map UI by iterating through the list and calling CreatePointerMarker for each.
void RecolorPointers ()
Method for settings to call for recolouring all pointers in the current list of instantiated objects.
void ClearPointer (GameObject pointerObj)
Focuses on clearing the pointer on map by finding and deleting the instance of it.
void RefreshPointers ()
Making use of ClearPointer(), removes all generated pointer objects and redraws them by fetching the latest list from the PointerController.
void OnPointerClicked (MapPointer pointer, GameObject pointerObj)
Triggered when a pointer is clicked.
void ShowPointerInfo (MapPointer pointer, GameObject pointerObj)
Shows the pointer info panel and populates it with the pointer's details.
void HidePointerInfo ()
Closes the Pointer Info Panel and removes all dynamically added listeners from the Edit and Delete buttons to prevent multiple calls.
System.Collections.IEnumerator LoadAllPointers (int xMin, int yMin)
Coroutine to load all pointers from the PointerController and initiate the rendering process.
Public Attributes
RectTransform mapPanelRect
Sprite pointerSprite
Sprite pointerDarkSprite
Sprite pointerHomeSprite
Sprite pointerDarkHomeSprite
GameObject pointerInfoPanel
TMP_Text pointerInfoText
Button editButton
Button deleteButton
Button closeInfoButton
MapController mapController
PointerController pointerController
PointerView pointerView
Private Member Functions
void CreatePointerMarker (MapPointer pointer, int zoom, int xMin, int yMin, float tileSize)
Creates a single pointer marker GameObject on the map.
void HighlightPointer (GameObject pointer)
Brightens the pointer to showcase responsiveness to user interaction (selection).
void ResetPointerColor (GameObject pointer)
Returns the Pointer to its original state (color/alpha) to indicate deselection.
Private Attributes
GameObject currentSelectedPointer
Tracks the currently selected pointer GameObject to manage highlighting.
Dictionary< GameObject, MapPointer > pointerObjDict = new()
A list of all instantiated pointer GameObjects currently rendered on the map.
int refXMin
Internal reference to the minimum X tile, used for redrawing pointers dynamically.
int refYMin
Internal reference to the minimum Y tile, used for redrawing pointers dynamically.
float refTileSize
Internal reference to the tile size, used for redrawing pointers dynamically.
Detailed Description
Responsible for rendering the users saved map pointers onto the UI map.
Responsibilities:
Convert pointer coordinates (lon/lat) to pixel positions through MapUtils Class
Assigns the correct Pointer Sprite to the pointer based on its home tag
Showcases information that the user has written about the pointer in a dedicated UI popup window
Includes buttons as means to access additional functionalities like editing/deleting the specified pointer
Author: Cheuk Hong Version: 1.0
Definition at line 28 of file PointerRenderer.cs.
Member Function Documentation
ClearPointer()
void Idenguefy.Boundaries.PointerRenderer.ClearPointer (GameObject pointerObj)
Focuses on clearing the pointer on map by finding and deleting the instance of it.
Internally, the entry still exists, and would have to be handled separately.
Parameters
pointerObj The pointer GameObject to destroy.
Definition at line 196 of file PointerRenderer.cs.
Referenced by RefreshPointers().
CreatePointerMarker()
void Idenguefy.Boundaries.PointerRenderer.CreatePointerMarker (MapPointer pointer, int zoom, int xMin, int yMin, float tileSize) private
Creates a single pointer marker GameObject on the map.
Calculates its position, assigns the correct sprite (based on HomeTag and theme), and adds an OnClick listener.
Parameters
pointer The MapPointer data object.
zoom The current map zoom level.
xMin The minimum X tile index of the map.
yMin The minimum Y tile index of the map.
tileSize The size (in pixels) of a single map tile.
Definition at line 113 of file PointerRenderer.cs.
References Idenguefy.Controllers.SettingsController.GetThemePref(), Idenguefy.Entities.MapPointer.HomeTag, Idenguefy.Entities.MapPointer.Latitude, Idenguefy.Entities.MapPointer.Longitude, Idenguefy.Controllers.MapUtils.LonLatToPixelRatio(), mapPanelRect, OnPointerClicked(), pointerDarkHomeSprite, pointerDarkSprite, pointerHomeSprite, pointerObjDict, and pointerSprite.
Referenced by DrawAllPointers().
DrawAllPointers()
void Idenguefy.Boundaries.PointerRenderer.DrawAllPointers (List< MapPointer > pointers, int zoom, int xMin, int yMin, float tileSize)
Draws all pointers onto the map UI by iterating through the list and calling CreatePointerMarker for each.
Parameters
pointers The list of MapPointer data objects to render.
zoom The current map zoom level.
xMin The minimum X tile index of the map.
yMin The minimum Y tile index of the map.
tileSize The size (in pixels) of a single map tile.
Definition at line 92 of file PointerRenderer.cs.
References CreatePointerMarker(), refTileSize, refXMin, and refYMin.
Referenced by LoadAllPointers(), and RefreshPointers().
HidePointerInfo()
void Idenguefy.Boundaries.PointerRenderer.HidePointerInfo ()
Closes the Pointer Info Panel and removes all dynamically added listeners from the Edit and Delete buttons to prevent multiple calls.
Definition at line 322 of file PointerRenderer.cs.
References currentSelectedPointer, deleteButton, editButton, Idenguefy.Boundaries.AnimationManager.Instance, pointerInfoPanel, ResetPointerColor(), and Idenguefy.Boundaries.AnimationManager.TogglePointerInfo().
HighlightPointer()
void Idenguefy.Boundaries.PointerRenderer.HighlightPointer (GameObject pointer) private
Brightens the pointer to showcase responsiveness to user interaction (selection).
Parameters
pointer The pointer GameObject to highlight.
Definition at line 233 of file PointerRenderer.cs.
Referenced by OnPointerClicked().
LoadAllPointers()
System.Collections.IEnumerator Idenguefy.Boundaries.PointerRenderer.LoadAllPointers (int xMin, int yMin)
Coroutine to load all pointers from the PointerController and initiate the rendering process.
Parameters
xMin The minimum X tile index of the map.
yMin The minimum Y tile index of the map.
Returns
An IEnumerator for the coroutine.
Definition at line 351 of file PointerRenderer.cs.
References DrawAllPointers(), mapController, and pointerController.
OnPointerClicked()
void Idenguefy.Boundaries.PointerRenderer.OnPointerClicked (MapPointer pointer, GameObject pointerObj)
Triggered when a pointer is clicked.
Manages selection highlighting and calls ShowPointerInfo to display details.
Parameters
pointer The data object for the clicked pointer.
pointerObj The GameObject of the clicked pointer.
Definition at line 263 of file PointerRenderer.cs.
References currentSelectedPointer, HighlightPointer(), Idenguefy.Entities.MapPointer.MapID, pointerInfoPanel, pointerInfoText, ResetPointerColor(), and ShowPointerInfo().
Referenced by CreatePointerMarker().
RecolorPointers()
void Idenguefy.Boundaries.PointerRenderer.RecolorPointers ()
Method for settings to call for recolouring all pointers in the current list of instantiated objects.
Definition at line 170 of file PointerRenderer.cs.
References Idenguefy.Controllers.SettingsController.GetThemePref(), pointerDarkHomeSprite, pointerDarkSprite, pointerHomeSprite, pointerObjDict, and pointerSprite.
RefreshPointers()
void Idenguefy.Boundaries.PointerRenderer.RefreshPointers ()
Making use of ClearPointer(), removes all generated pointer objects and redraws them by fetching the latest list from the PointerController.
Definition at line 211 of file PointerRenderer.cs.
References ClearPointer(), DrawAllPointers(), mapController, pointerController, pointerObjDict, refTileSize, refXMin, and refYMin.
ResetPointerColor()
void Idenguefy.Boundaries.PointerRenderer.ResetPointerColor (GameObject pointer) private
Returns the Pointer to its original state (color/alpha) to indicate deselection.
Parameters
pointer The pointer GameObject to reset.
Definition at line 245 of file PointerRenderer.cs.
Referenced by HidePointerInfo(), and OnPointerClicked().
ShowPointerInfo()
void Idenguefy.Boundaries.PointerRenderer.ShowPointerInfo (MapPointer pointer, GameObject pointerObj)
Shows the pointer info panel and populates it with the pointer's details.
Also dynamically assigns listeners to the Edit and Delete buttons.
Parameters
pointer The data object for the selected pointer.
pointerObj The GameObject of the selected pointer (not currently used here).
Definition at line 293 of file PointerRenderer.cs.
References deleteButton, editButton, Idenguefy.Boundaries.AnimationManager.Instance, pointerView, and Idenguefy.Boundaries.AnimationManager.TogglePointerInfo().
Referenced by OnPointerClicked().
Member Data Documentation
closeInfoButton
Button Idenguefy.Boundaries.PointerRenderer.closeInfoButton
Definition at line 52 of file PointerRenderer.cs.
currentSelectedPointer
GameObject Idenguefy.Boundaries.PointerRenderer.currentSelectedPointer private
Tracks the currently selected pointer GameObject to manage highlighting.
Definition at line 57 of file PointerRenderer.cs.
Referenced by HidePointerInfo(), and OnPointerClicked().
deleteButton
Button Idenguefy.Boundaries.PointerRenderer.deleteButton
Definition at line 50 of file PointerRenderer.cs.
Referenced by HidePointerInfo(), and ShowPointerInfo().
editButton
Button Idenguefy.Boundaries.PointerRenderer.editButton
Definition at line 48 of file PointerRenderer.cs.
Referenced by HidePointerInfo(), and ShowPointerInfo().
mapController
MapController Idenguefy.Boundaries.PointerRenderer.mapController
Definition at line 73 of file PointerRenderer.cs.
Referenced by LoadAllPointers(), and RefreshPointers().
mapPanelRect
RectTransform Idenguefy.Boundaries.PointerRenderer.mapPanelRect
Definition at line 32 of file PointerRenderer.cs.
Referenced by CreatePointerMarker().
pointerController
PointerController Idenguefy.Boundaries.PointerRenderer.pointerController
Definition at line 75 of file PointerRenderer.cs.
Referenced by LoadAllPointers(), and RefreshPointers().
pointerDarkHomeSprite
Sprite Idenguefy.Boundaries.PointerRenderer.pointerDarkHomeSprite
Definition at line 40 of file PointerRenderer.cs.
Referenced by CreatePointerMarker(), and RecolorPointers().
pointerDarkSprite
Sprite Idenguefy.Boundaries.PointerRenderer.pointerDarkSprite
Definition at line 36 of file PointerRenderer.cs.
Referenced by CreatePointerMarker(), and RecolorPointers().
pointerHomeSprite
Sprite Idenguefy.Boundaries.PointerRenderer.pointerHomeSprite
Definition at line 38 of file PointerRenderer.cs.
Referenced by CreatePointerMarker(), and RecolorPointers().
pointerInfoPanel
GameObject Idenguefy.Boundaries.PointerRenderer.pointerInfoPanel
Definition at line 44 of file PointerRenderer.cs.
Referenced by HidePointerInfo(), and OnPointerClicked().
pointerInfoText
TMP_Text Idenguefy.Boundaries.PointerRenderer.pointerInfoText
Definition at line 46 of file PointerRenderer.cs.
Referenced by OnPointerClicked().
pointerObjDict
Dictionary<GameObject, MapPointer> Idenguefy.Boundaries.PointerRenderer.pointerObjDict = new() private
A list of all instantiated pointer GameObjects currently rendered on the map.
Definition at line 62 of file PointerRenderer.cs.
Referenced by CreatePointerMarker(), RecolorPointers(), and RefreshPointers().
pointerSprite
Sprite Idenguefy.Boundaries.PointerRenderer.pointerSprite
Definition at line 34 of file PointerRenderer.cs.
Referenced by CreatePointerMarker(), and RecolorPointers().
pointerView
PointerView Idenguefy.Boundaries.PointerRenderer.pointerView
Definition at line 81 of file PointerRenderer.cs.
Referenced by ShowPointerInfo().
refTileSize
float Idenguefy.Boundaries.PointerRenderer.refTileSize private
Internal reference to the tile size, used for redrawing pointers dynamically.
Definition at line 69 of file PointerRenderer.cs.
Referenced by DrawAllPointers(), and RefreshPointers().
refXMin
int Idenguefy.Boundaries.PointerRenderer.refXMin private
Internal reference to the minimum X tile, used for redrawing pointers dynamically.
Definition at line 65 of file PointerRenderer.cs.
Referenced by DrawAllPointers(), and RefreshPointers().
refYMin
int Idenguefy.Boundaries.PointerRenderer.refYMin private
Internal reference to the minimum Y tile, used for redrawing pointers dynamically.
Definition at line 67 of file PointerRenderer.cs.
Referenced by DrawAllPointers(), and RefreshPointers().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/PointerRenderer.cs