Idenguefy: Idenguefy.Boundaries.SearchView Class Reference
Idenguefy.Boundaries.SearchView Class Reference
Manages all the interactions related to the search bar and its dropdown results list.
Public Member Functions
void Start ()
Initializes the search view by adding a listener to the search input field.
void OnSearchResultClicked (MapSearchResult result)
Called when a user clicks a specific search result from the list.
void OnSearchSubmit (string query)
Public entry point to start the search coroutine when the user submits a query.
IEnumerator OnSearchSubmitCoroutine (string query)
Coroutine that handles the full search process:
void DisplaySearchBar (TMP_InputField searchBar)
Reveals the search input bar to the user (legacy or future use).
void DisplaySearchSuggestion (MapSearchResult searchItem)
Instantiates and populates a single search result prefab in the results list.
void DestroyAllSearchResults ()
Clears all displayed search results from the container.
Public Attributes
SearchController searchController
MapView mapView
RectTransform searchResultContainer
GameObject searchResultsView
GameObject searchResultPrefab
GameObject emptyStateText
TMP_InputField searchInputField
Detailed Description
Manages all the interactions related to the search bar and its dropdown results list.
Author: Eben, Xavier Version: 1.0
Definition at line 19 of file SearchView.cs.
Member Function Documentation
DestroyAllSearchResults()
void Idenguefy.Boundaries.SearchView.DestroyAllSearchResults ()
Clears all displayed search results from the container.
Definition at line 135 of file SearchView.cs.
References searchResultContainer, and searchResultPrefab.
Referenced by OnSearchSubmitCoroutine().
DisplaySearchBar()
void Idenguefy.Boundaries.SearchView.DisplaySearchBar (TMP_InputField searchBar)
Reveals the search input bar to the user (legacy or future use).
Parameters
searchBar The input field to show.
Definition at line 106 of file SearchView.cs.
DisplaySearchSuggestion()
void Idenguefy.Boundaries.SearchView.DisplaySearchSuggestion (MapSearchResult searchItem)
Instantiates and populates a single search result prefab in the results list.
Parameters
searchItem The MapSearchResult data to display.
Definition at line 115 of file SearchView.cs.
References Idenguefy.Entities.MapSearchResult.detail, Idenguefy.Entities.MapSearchResult.name, OnSearchResultClicked(), searchResultContainer, and searchResultPrefab.
Referenced by OnSearchSubmitCoroutine().
OnSearchResultClicked()
void Idenguefy.Boundaries.SearchView.OnSearchResultClicked (MapSearchResult result)
Called when a user clicks a specific search result from the list.
Receneters the map to that result's location and hides the results list.
Parameters
result The MapSearchResult data object that was clicked.
Definition at line 56 of file SearchView.cs.
References Idenguefy.Entities.MapSearchResult.coord, mapView, and searchResultsView.
Referenced by DisplaySearchSuggestion().
OnSearchSubmit()
void Idenguefy.Boundaries.SearchView.OnSearchSubmit (string query)
Public entry point to start the search coroutine when the user submits a query.
Parameters
query The text from the search input field.
Definition at line 66 of file SearchView.cs.
References OnSearchSubmitCoroutine().
Referenced by Start().
OnSearchSubmitCoroutine()
IEnumerator Idenguefy.Boundaries.SearchView.OnSearchSubmitCoroutine (string query)
Coroutine that handles the full search process:
Clears old results.
Calls the SearchController to fetch new results.
Displays the new results or an empty state message.
Parameters
query The search query.
Returns
An IEnumerator for coroutine execution.
Definition at line 80 of file SearchView.cs.
References DestroyAllSearchResults(), DisplaySearchSuggestion(), searchController, and searchResultsView.
Referenced by OnSearchSubmit().
Start()
void Idenguefy.Boundaries.SearchView.Start ()
Initializes the search view by adding a listener to the search input field.
Definition at line 44 of file SearchView.cs.
References OnSearchSubmit(), and searchInputField.
Member Data Documentation
emptyStateText
GameObject Idenguefy.Boundaries.SearchView.emptyStateText
Definition at line 37 of file SearchView.cs.
mapView
MapView Idenguefy.Boundaries.SearchView.mapView
Definition at line 27 of file SearchView.cs.
Referenced by OnSearchResultClicked().
searchController
SearchController Idenguefy.Boundaries.SearchView.searchController
Definition at line 23 of file SearchView.cs.
Referenced by OnSearchSubmitCoroutine().
searchInputField
TMP_InputField Idenguefy.Boundaries.SearchView.searchInputField
Definition at line 39 of file SearchView.cs.
Referenced by Start().
searchResultContainer
RectTransform Idenguefy.Boundaries.SearchView.searchResultContainer
Definition at line 31 of file SearchView.cs.
Referenced by DestroyAllSearchResults(), and DisplaySearchSuggestion().
searchResultPrefab
GameObject Idenguefy.Boundaries.SearchView.searchResultPrefab
Definition at line 35 of file SearchView.cs.
Referenced by DestroyAllSearchResults(), and DisplaySearchSuggestion().
searchResultsView
GameObject Idenguefy.Boundaries.SearchView.searchResultsView
Definition at line 33 of file SearchView.cs.
Referenced by OnSearchResultClicked(), and OnSearchSubmitCoroutine().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/SearchView.cs