Idenguefy: Idenguefy.Boundaries.ClusterRenderer Class Reference
Idenguefy.Boundaries.ClusterRenderer Class Reference
Responsible for rendering dengue clusters on the UI map as colored circles.
Public Member Functions
void DrawClusterCircles (List< DengueCluster > clusters, int zoom, int xMin, int yMin, float tileSize)
Draws circles for all dengue clusters.
void HideClusterInfo ()
Hides the info panel (for Close button).
IEnumerator LoadAllClusters (int xMin, int yMin)
Retrieves a list of all clusters from the API to be handled by other methods in ClusterRenderer.
Public Attributes
RectTransform mapPanelRect
Sprite circleSprite
GameObject clusterInfoPanel
TMP_Text clusterInfoText
Button closeInfoButton
MapController mapController
ClusterController clusterController
Private Member Functions
void CreateCircle (DengueCluster cluster, int zoom, int xMin, int yMin, float tileSize)
Draws the circle for a cluster and sets its details and colors based off retrieved information.
void OnClusterClicked (DengueCluster cluster, GameObject circleObj)
Triggered when a cluster circle is clicked Shows its details in the info panel.
void HighlightCircle (GameObject circle)
Brightens the Cluster circle to showcase responsiveness to user interaction.
void ResetCircleColor (GameObject circle)
Returns the Cluster circle to its original state to indicate deselection to the user.
IEnumerator FadeInInfoPanel ()
Color GetSeverityColor (string severity)
Determines colour to set the Cluster Circle based on given severity.
Private Attributes
GameObject currentSelectedCircle
Detailed Description
Responsible for rendering dengue clusters on the UI map as colored circles.
Responsibilities:
Convert cluster coordinates (lon/lat) to pixel positions through MapUtils Class
Compute approximate cluster radius from polygon points through MapUtils Class
Create semi-transparent colored circle UI elements inside mapPanelRect
Color code clusters by severity
Shows information about the cluster in a dedicated UI popup window
Adjusts for map panel offset and pivot alignment to ensure accurate placement Creates a color coded cluster based on serverity
Author: Xavier Version: 2.0 Notes: N/A
Definition at line 30 of file ClusterRenderer.cs.
Member Function Documentation
CreateCircle()
void Idenguefy.Boundaries.ClusterRenderer.CreateCircle (DengueCluster cluster, int zoom, int xMin, int yMin, float tileSize) private
Draws the circle for a cluster and sets its details and colors based off retrieved information.
Definition at line 60 of file ClusterRenderer.cs.
References circleSprite, Idenguefy.Entities.DengueCluster.Coordinates, GetSeverityColor(), Idenguefy.Controllers.MapUtils.LonLatToPixelRatio(), mapPanelRect, OnClusterClicked(), and Idenguefy.Entities.DengueCluster.Severity.
Referenced by DrawClusterCircles().
DrawClusterCircles()
void Idenguefy.Boundaries.ClusterRenderer.DrawClusterCircles (List< DengueCluster > clusters, int zoom, int xMin, int yMin, float tileSize)
Draws circles for all dengue clusters.
Definition at line 50 of file ClusterRenderer.cs.
References CreateCircle().
Referenced by LoadAllClusters().
FadeInInfoPanel()
IEnumerator Idenguefy.Boundaries.ClusterRenderer.FadeInInfoPanel () private
Definition at line 174 of file ClusterRenderer.cs.
References clusterInfoPanel.
GetSeverityColor()
Color Idenguefy.Boundaries.ClusterRenderer.GetSeverityColor (string severity) private
Determines colour to set the Cluster Circle based on given severity.
Definition at line 209 of file ClusterRenderer.cs.
Referenced by CreateCircle().
HideClusterInfo()
void Idenguefy.Boundaries.ClusterRenderer.HideClusterInfo ()
Hides the info panel (for Close button).
Definition at line 198 of file ClusterRenderer.cs.
References clusterInfoPanel, currentSelectedCircle, and ResetCircleColor().
HighlightCircle()
void Idenguefy.Boundaries.ClusterRenderer.HighlightCircle (GameObject circle) private
Brightens the Cluster circle to showcase responsiveness to user interaction.
Definition at line 153 of file ClusterRenderer.cs.
Referenced by OnClusterClicked().
LoadAllClusters()
IEnumerator Idenguefy.Boundaries.ClusterRenderer.LoadAllClusters (int xMin, int yMin)
Retrieves a list of all clusters from the API to be handled by other methods in ClusterRenderer.
Definition at line 221 of file ClusterRenderer.cs.
References clusterController, DrawClusterCircles(), and mapController.
OnClusterClicked()
void Idenguefy.Boundaries.ClusterRenderer.OnClusterClicked (DengueCluster cluster, GameObject circleObj) private
Triggered when a cluster circle is clicked Shows its details in the info panel.
Definition at line 121 of file ClusterRenderer.cs.
References Idenguefy.Boundaries.AnimationManager.clusterInfoIsExpanded, clusterInfoPanel, clusterInfoText, currentSelectedCircle, HighlightCircle(), Idenguefy.Boundaries.AnimationManager.Instance, ResetCircleColor(), and Idenguefy.Boundaries.AnimationManager.ToggleClusterInfo().
Referenced by CreateCircle().
ResetCircleColor()
void Idenguefy.Boundaries.ClusterRenderer.ResetCircleColor (GameObject circle) private
Returns the Cluster circle to its original state to indicate deselection to the user.
Definition at line 162 of file ClusterRenderer.cs.
Referenced by HideClusterInfo(), and OnClusterClicked().
Member Data Documentation
circleSprite
Sprite Idenguefy.Boundaries.ClusterRenderer.circleSprite
Definition at line 34 of file ClusterRenderer.cs.
Referenced by CreateCircle().
closeInfoButton
Button Idenguefy.Boundaries.ClusterRenderer.closeInfoButton
Definition at line 39 of file ClusterRenderer.cs.
clusterController
ClusterController Idenguefy.Boundaries.ClusterRenderer.clusterController
Definition at line 45 of file ClusterRenderer.cs.
Referenced by LoadAllClusters().
clusterInfoPanel
GameObject Idenguefy.Boundaries.ClusterRenderer.clusterInfoPanel
Definition at line 37 of file ClusterRenderer.cs.
Referenced by FadeInInfoPanel(), HideClusterInfo(), and OnClusterClicked().
clusterInfoText
TMP_Text Idenguefy.Boundaries.ClusterRenderer.clusterInfoText
Definition at line 38 of file ClusterRenderer.cs.
Referenced by OnClusterClicked().
currentSelectedCircle
GameObject Idenguefy.Boundaries.ClusterRenderer.currentSelectedCircle private
Definition at line 41 of file ClusterRenderer.cs.
Referenced by HideClusterInfo(), and OnClusterClicked().
mapController
MapController Idenguefy.Boundaries.ClusterRenderer.mapController
Definition at line 44 of file ClusterRenderer.cs.
Referenced by LoadAllClusters().
mapPanelRect
RectTransform Idenguefy.Boundaries.ClusterRenderer.mapPanelRect
Definition at line 33 of file ClusterRenderer.cs.
Referenced by CreateCircle().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/ClusterRenderer.cs