Idenguefy: Idenguefy.Controllers.ClusterController Class Reference
Idenguefy.Controllers.ClusterController Class Reference
Handles the management and retrieval of dengue cluster data in the Idenguefy system.
Public Member Functions
IEnumerator FetchClusterData ()
Public method to fetch cluster data using the attached API handler.
void RefreshClusters ()
Manually refresh cluster data.
DengueCluster ReadCluster (string locationID)
Retrieves a specific cluster by ID.
Public Attributes
Cluster_API_Handler apiHandler
Properties
List< DengueCluster > Clusters [get]
Private Member Functions
void Awake ()
void Start ()
Detailed Description
Handles the management and retrieval of dengue cluster data in the Idenguefy system.
Responsibilities:
Interfaces with Cluster_API_Handler to fetch cluster data.
Provides centralized access to the current list of dengue clusters.
Supports manual and automatic data refresh.
Author: Napatr
Version: 1.0
Definition at line 20 of file ClusterController.cs.
Member Function Documentation
Awake()
void Idenguefy.Controllers.ClusterController.Awake () private
Definition at line 27 of file ClusterController.cs.
References apiHandler.
FetchClusterData()
IEnumerator Idenguefy.Controllers.ClusterController.FetchClusterData ()
Public method to fetch cluster data using the attached API handler.
This wraps the API call and can be safely called by other controllers.
Definition at line 47 of file ClusterController.cs.
References apiHandler.
Referenced by RefreshClusters(), and Start().
ReadCluster()
DengueCluster Idenguefy.Controllers.ClusterController.ReadCluster (string locationID)
Retrieves a specific cluster by ID.
Definition at line 79 of file ClusterController.cs.
References apiHandler.
RefreshClusters()
void Idenguefy.Controllers.ClusterController.RefreshClusters ()
Manually refresh cluster data.
Definition at line 64 of file ClusterController.cs.
References apiHandler, and FetchClusterData().
Start()
void Idenguefy.Controllers.ClusterController.Start () private
Definition at line 36 of file ClusterController.cs.
References apiHandler, and FetchClusterData().
Member Data Documentation
apiHandler
Cluster_API_Handler Idenguefy.Controllers.ClusterController.apiHandler
Definition at line 23 of file ClusterController.cs.
Referenced by Awake(), FetchClusterData(), ReadCluster(), RefreshClusters(), and Start().
Property Documentation
Clusters
List<DengueCluster> Idenguefy.Controllers.ClusterController.Clusters get
Definition at line 25 of file ClusterController.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/ClusterController.cs