Idenguefy: Idenguefy.Boundaries.PointerView Class Reference
Idenguefy.Boundaries.PointerView Class Reference
Responsible for rendering the saved map pointers additional UI interfaces.
Public Member Functions
void OnLongPressDetected (Vector2 touchCoord)
Runs when the application detects a user is pressing and holding on the screen.
void ShowCreatePanel ()
Brings up the Create/Edit interface, configured for 'Create' mode.
void ConfirmCreate ()
Carries out Pointer Creation logic based on the data in the input fields.
void ShowEditPanel (MapPointer pointer)
Brings up the Create/Edit interface, configured for 'Edit' mode and pre-filled with the pointer's existing data.
void ConfirmEdit ()
Carries out edit operations when user confirms the edit, using the data from the input fields.
void HideDualPanel ()
Hides the create/edit panel and resets all input fields and listeners.
void ConfirmCreateOrEdit ()
Utilises the corresponding Create or Edit confirmation logic based on the isEditMode flag, then refreshes the pointers on the map.
void ShowDeletePanel ()
Shows the delete confirmation screen.
void HideDeletePanel ()
Hides the delete confirmation screen.
void ConfirmDelete ()
If user selects the confirm button, proceed with pointer deletion and refresh the pointers on the map UI if successful.
void RefreshPointerList ()
Reloads the list of all pointer entries onto the corresponding UI window.
void ShowPointerList ()
Calls to reload and show the list of all pointer entries onto the corresponding UI window.
void HidePointerList ()
Closes the UI window where the list of all pointer entries are on.
Public Attributes
PointerController pointerController
MapController mapController
PointerRenderer pointerRenderer
GameObject dualPurposePanel
TMP_Text dualPurposeTitle
TMP_InputField dualNameInput
TMP_InputField dualAreaInput
TMP_InputField dualNoteInput
Toggle homeToggles
string clickedPointerId
Stores the MapID of the pointer currently being interacted with (e.g., clicked, edited, or deleted).
GameObject deletePanel
GameObject pointerList
RectTransform pointerEntryContainer
GameObject pointerEntryPrefab
GameObject emptyStateText
Sprite pointerSprite
Sprite pointerHomeSprite
Private Attributes
List< MapPointer > pointers
Internal list of MapPointer data, (unused, data is fetched on demand).
List< GameObject > pointerEntries = new()
A list of all instantiated pointer entry GameObjects in the scrollable list.
bool isEditMode = false
Flag to determine if the dual-purpose panel is in 'Edit' mode (true) or 'Create' mode (false).
double longPressTime = 1
The duration (in seconds) a user must press and hold (unused, logic is in MapView).
Vector2 touchCoord
The screen coordinate from a long press, used for creating a new pointer.
float lon
The geographic coordinate (lon, lat) from a long press (unused).
float float lat geoCoord
Detailed Description
Responsible for rendering the saved map pointers additional UI interfaces.
Responsibilities:
Displays respective popup windows for Creating/Editing/Deleting a pointer
Displays confirmation for deleting a pointer
Displays a list of all pointers created by the user
Author: Cheuk Hong Version: 1.0
Definition at line 30 of file PointerView.cs.
Member Function Documentation
ConfirmCreate()
void Idenguefy.Boundaries.PointerView.ConfirmCreate ()
Carries out Pointer Creation logic based on the data in the input fields.
Definition at line 127 of file PointerView.cs.
References dualAreaInput, dualNameInput, dualNoteInput, HideDualPanel(), homeToggles, isEditMode, pointerController, and touchCoord.
Referenced by ConfirmCreateOrEdit().
ConfirmCreateOrEdit()
void Idenguefy.Boundaries.PointerView.ConfirmCreateOrEdit ()
Utilises the corresponding Create or Edit confirmation logic based on the isEditMode flag, then refreshes the pointers on the map.
Definition at line 215 of file PointerView.cs.
References ConfirmCreate(), ConfirmEdit(), isEditMode, and pointerRenderer.
ConfirmDelete()
void Idenguefy.Boundaries.PointerView.ConfirmDelete ()
If user selects the confirm button, proceed with pointer deletion and refresh the pointers on the map UI if successful.
Definition at line 245 of file PointerView.cs.
References clickedPointerId, pointerController, and pointerRenderer.
ConfirmEdit()
void Idenguefy.Boundaries.PointerView.ConfirmEdit ()
Carries out edit operations when user confirms the edit, using the data from the input fields.
Definition at line 175 of file PointerView.cs.
References clickedPointerId, dualAreaInput, dualNameInput, dualNoteInput, HideDualPanel(), homeToggles, and pointerController.
Referenced by ConfirmCreateOrEdit().
HideDeletePanel()
void Idenguefy.Boundaries.PointerView.HideDeletePanel ()
Hides the delete confirmation screen.
Definition at line 235 of file PointerView.cs.
References deletePanel.
HideDualPanel()
void Idenguefy.Boundaries.PointerView.HideDualPanel ()
Hides the create/edit panel and resets all input fields and listeners.
Definition at line 192 of file PointerView.cs.
References Idenguefy.Boundaries.AnimationManager.Instance, isEditMode, pointerRenderer, and Idenguefy.Boundaries.AnimationManager.ToggleDualPointerView().
Referenced by ConfirmCreate(), and ConfirmEdit().
HidePointerList()
void Idenguefy.Boundaries.PointerView.HidePointerList ()
Closes the UI window where the list of all pointer entries are on.
Definition at line 343 of file PointerView.cs.
References Idenguefy.Boundaries.AnimationManager.Instance, and Idenguefy.Boundaries.AnimationManager.TogglePointerList().
OnLongPressDetected()
void Idenguefy.Boundaries.PointerView.OnLongPressDetected (Vector2 touchCoord)
Runs when the application detects a user is pressing and holding on the screen.
This is called by MapView.ReadTouch().
Parameters
touchCoord The screen position (in pixels) of the long press.
Definition at line 106 of file PointerView.cs.
References ShowCreatePanel(), and touchCoord.
RefreshPointerList()
void Idenguefy.Boundaries.PointerView.RefreshPointerList ()
Reloads the list of all pointer entries onto the corresponding UI window.
Definition at line 258 of file PointerView.cs.
References emptyStateText, Idenguefy.Entities.MapPointer.HomeTag, pointerController, pointerEntries, pointerEntryContainer, pointerEntryPrefab, pointerHomeSprite, pointers, and pointerSprite.
Referenced by ShowPointerList().
ShowCreatePanel()
void Idenguefy.Boundaries.PointerView.ShowCreatePanel ()
Brings up the Create/Edit interface, configured for 'Create' mode.
Definition at line 115 of file PointerView.cs.
References Idenguefy.Boundaries.AnimationManager.Instance, isEditMode, and Idenguefy.Boundaries.AnimationManager.ToggleDualPointerView().
Referenced by OnLongPressDetected().
ShowDeletePanel()
void Idenguefy.Boundaries.PointerView.ShowDeletePanel ()
Shows the delete confirmation screen.
Definition at line 225 of file PointerView.cs.
References deletePanel.
ShowEditPanel()
void Idenguefy.Boundaries.PointerView.ShowEditPanel (MapPointer pointer)
Brings up the Create/Edit interface, configured for 'Edit' mode and pre-filled with the pointer's existing data.
Parameters
pointer The MapPointer data object to edit.
Definition at line 154 of file PointerView.cs.
References Idenguefy.Entities.MapPointer.AreaName, Idenguefy.Entities.MapPointer.HomeTag, Idenguefy.Boundaries.AnimationManager.Instance, isEditMode, Idenguefy.Entities.MapPointer.Name, Idenguefy.Entities.MapPointer.Note, Idenguefy.Boundaries.AnimationManager.ToggleDualPointerView(), and Idenguefy.Boundaries.AnimationManager.TogglePointerInfo().
ShowPointerList()
void Idenguefy.Boundaries.PointerView.ShowPointerList ()
Calls to reload and show the list of all pointer entries onto the corresponding UI window.
Definition at line 335 of file PointerView.cs.
References RefreshPointerList().
Member Data Documentation
clickedPointerId
string Idenguefy.Boundaries.PointerView.clickedPointerId
Stores the MapID of the pointer currently being interacted with (e.g., clicked, edited, or deleted).
Definition at line 56 of file PointerView.cs.
Referenced by ConfirmDelete(), and ConfirmEdit().
deletePanel
GameObject Idenguefy.Boundaries.PointerView.deletePanel
Definition at line 60 of file PointerView.cs.
Referenced by HideDeletePanel(), and ShowDeletePanel().
dualAreaInput
TMP_InputField Idenguefy.Boundaries.PointerView.dualAreaInput
Definition at line 47 of file PointerView.cs.
Referenced by ConfirmCreate(), and ConfirmEdit().
dualNameInput
TMP_InputField Idenguefy.Boundaries.PointerView.dualNameInput
Definition at line 45 of file PointerView.cs.
Referenced by ConfirmCreate(), and ConfirmEdit().
dualNoteInput
TMP_InputField Idenguefy.Boundaries.PointerView.dualNoteInput
Definition at line 49 of file PointerView.cs.
Referenced by ConfirmCreate(), and ConfirmEdit().
dualPurposePanel
GameObject Idenguefy.Boundaries.PointerView.dualPurposePanel
Definition at line 41 of file PointerView.cs.
dualPurposeTitle
TMP_Text Idenguefy.Boundaries.PointerView.dualPurposeTitle
Definition at line 43 of file PointerView.cs.
emptyStateText
GameObject Idenguefy.Boundaries.PointerView.emptyStateText
Definition at line 70 of file PointerView.cs.
Referenced by RefreshPointerList().
geoCoord
float float lat Idenguefy.Boundaries.PointerView.geoCoord private
Definition at line 99 of file PointerView.cs.
homeToggles
Toggle Idenguefy.Boundaries.PointerView.homeToggles
Definition at line 51 of file PointerView.cs.
Referenced by ConfirmCreate(), and ConfirmEdit().
isEditMode
bool Idenguefy.Boundaries.PointerView.isEditMode = false private
Flag to determine if the dual-purpose panel is in 'Edit' mode (true) or 'Create' mode (false).
Definition at line 87 of file PointerView.cs.
Referenced by ConfirmCreate(), ConfirmCreateOrEdit(), HideDualPanel(), ShowCreatePanel(), and ShowEditPanel().
lon
float Idenguefy.Boundaries.PointerView.lon private
The geographic coordinate (lon, lat) from a long press (unused).
Definition at line 99 of file PointerView.cs.
longPressTime
double Idenguefy.Boundaries.PointerView.longPressTime = 1 private
The duration (in seconds) a user must press and hold (unused, logic is in MapView).
Definition at line 91 of file PointerView.cs.
mapController
MapController Idenguefy.Boundaries.PointerView.mapController
Definition at line 36 of file PointerView.cs.
pointerController
PointerController Idenguefy.Boundaries.PointerView.pointerController
Definition at line 34 of file PointerView.cs.
Referenced by ConfirmCreate(), ConfirmDelete(), ConfirmEdit(), and RefreshPointerList().
pointerEntries
List<GameObject> Idenguefy.Boundaries.PointerView.pointerEntries = new() private
A list of all instantiated pointer entry GameObjects in the scrollable list.
Definition at line 83 of file PointerView.cs.
Referenced by RefreshPointerList().
pointerEntryContainer
RectTransform Idenguefy.Boundaries.PointerView.pointerEntryContainer
Definition at line 66 of file PointerView.cs.
Referenced by RefreshPointerList().
pointerEntryPrefab
GameObject Idenguefy.Boundaries.PointerView.pointerEntryPrefab
Definition at line 68 of file PointerView.cs.
Referenced by RefreshPointerList().
pointerHomeSprite
Sprite Idenguefy.Boundaries.PointerView.pointerHomeSprite
Definition at line 74 of file PointerView.cs.
Referenced by RefreshPointerList().
pointerList
GameObject Idenguefy.Boundaries.PointerView.pointerList
Definition at line 64 of file PointerView.cs.
pointerRenderer
PointerRenderer Idenguefy.Boundaries.PointerView.pointerRenderer
Definition at line 38 of file PointerView.cs.
Referenced by ConfirmCreateOrEdit(), ConfirmDelete(), and HideDualPanel().
pointers
List<MapPointer> Idenguefy.Boundaries.PointerView.pointers private
Internal list of MapPointer data, (unused, data is fetched on demand).
Definition at line 79 of file PointerView.cs.
Referenced by RefreshPointerList().
pointerSprite
Sprite Idenguefy.Boundaries.PointerView.pointerSprite
Definition at line 72 of file PointerView.cs.
Referenced by RefreshPointerList().
touchCoord
Vector2 Idenguefy.Boundaries.PointerView.touchCoord private
The screen coordinate from a long press, used for creating a new pointer.
Definition at line 95 of file PointerView.cs.
Referenced by ConfirmCreate(), and OnLongPressDetected().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/PointerView.cs