Idenguefy: Idenguefy.Controllers.MapUtils Class Reference
Idenguefy.Controllers.MapUtils Class Reference
Utility class providing coordinate conversion functions for the map system.
Static Public Member Functions
static void LonLatToPixelRatio (double longitude, double latitude, int zoom, int xMin, int yMin, out double xPixelRatio, out double yPixelRatio)
Converts geographic coordinates (longitude, latitude) into a pixel ratio relative to a minimum tile boundary.
static void LonLatToTile (double longitude, double latitude, int zoom, out int x, out int y)
Converts geographic coordinates (longitude, latitude) into Web Mercator tile indices (X, Y) for a given zoom level.
static double calcNormalizedX (double longitude)
Helper function to calculate the normalized X coordinate (0.0 to 1.0) from longitude.
static double calcNormalizedY (double latitude)
Helper function to calculate the normalized Y coordinate (0.0 to 1.0) from latitude.
static double HaversineDistance (float lon1, float lat1, float lon2, float lat2)
Calculates the great-circle distance between two geographic points (lon/lat) using the Haversine formula.
Detailed Description
Utility class providing coordinate conversion functions for the map system.
Converts longitude/latitude into tile indices or pixel ratios according to the Web Mercator projection.
Author: Eben, Ryan, Xavier Version: 1.1 Notes: N/A
Definition at line 18 of file MapUtils.cs.
Member Function Documentation
calcNormalizedX()
double Idenguefy.Controllers.MapUtils.calcNormalizedX (double longitude) static
Helper function to calculate the normalized X coordinate (0.0 to 1.0) from longitude.
Parameters
longitude The geographic longitude coordinate.
Returns
The normalized X value (0.0 to 1.0) based on the Mercator projection.
Definition at line 64 of file MapUtils.cs.
Referenced by LonLatToPixelRatio(), and LonLatToTile().
calcNormalizedY()
double Idenguefy.Controllers.MapUtils.calcNormalizedY (double latitude) static
Helper function to calculate the normalized Y coordinate (0.0 to 1.0) from latitude.
Parameters
latitude The geographic latitude coordinate.
Returns
The normalized Y value (0.0 to 1.0) based on the Mercator projection.
Definition at line 75 of file MapUtils.cs.
Referenced by LonLatToPixelRatio(), and LonLatToTile().
HaversineDistance()
double Idenguefy.Controllers.MapUtils.HaversineDistance (float lon1, float lat1, float lon2, float lat2) static
Calculates the great-circle distance between two geographic points (lon/lat) using the Haversine formula.
Parameters
lon1 Longitude of the first point.
lat1 Latitude of the first point.
lon2 Longitude of the second point.
lat2 Latitude of the second point.
Returns
The distance between the two points in kilometers (based on Earth radius R = 6371km).
Definition at line 90 of file MapUtils.cs.
Referenced by Idenguefy.Controllers.AlertManager.EvaluateAlerts().
LonLatToPixelRatio()
void Idenguefy.Controllers.MapUtils.LonLatToPixelRatio (double longitude, double latitude, int zoom, int xMin, int yMin, out double xPixelRatio, out double yPixelRatio) static
Converts geographic coordinates (longitude, latitude) into a pixel ratio relative to a minimum tile boundary.
This is used to calculate the precise position of a point within the map panel, offset by the top-left tile (xMin, yMin).
Parameters
longitude The geographic longitude coordinate.
latitude The geographic latitude coordinate.
zoom The current map zoom level.
xMin The minimum X tile index (left-most tile) of the map boundary.
yMin The minimum Y tile index (top-most tile) of the map boundary.
xPixelRatio Output: The calculated X position as a tile ratio, offset from xMin.
yPixelRatio Output: The calculated Y position as a tile ratio, offset from yMin.
Definition at line 31 of file MapUtils.cs.
References calcNormalizedX(), and calcNormalizedY().
Referenced by Idenguefy.Boundaries.ClusterRenderer.CreateCircle(), Idenguefy.Boundaries.PointerRenderer.CreatePointerMarker(), Idenguefy.Controllers.MapController.GeoToScreen(), and Idenguefy.Boundaries.LiveLocationRenderer.RenderLiveLocation().
LonLatToTile()
void Idenguefy.Controllers.MapUtils.LonLatToTile (double longitude, double latitude, int zoom, out int x, out int y) static
Converts geographic coordinates (longitude, latitude) into Web Mercator tile indices (X, Y) for a given zoom level.
Parameters
longitude The geographic longitude coordinate.
latitude The geographic latitude coordinate.
zoom The current map zoom level.
x Output: The calculated tile X index.
y Output: The calculated tile Y index.
Definition at line 50 of file MapUtils.cs.
References calcNormalizedX(), and calcNormalizedY().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/MapUtils.cs