Idenguefy: TileCacheManager Class Reference
TileCacheManager Class Reference
Manages the disk-based caching of map tiles.
Public Member Functions
bool checkAnyPendingLoad (int x, int y)
Checks if a specific tile is currently being written to the cache.
void CacheTileData (Texture2D tileTexture, int x, int y)
Caches a tile texture to disk.
async Task< Texture2D > RetrieveCachedTile (int x, int y)
Asynchronously retrieves a cached tile from the disk.
void ClearTileCache ()
Clears the custom tile cache directory and Unity's built-in cache.
Properties
static string CachePath [get]
Gets the platform-specific root path for the tile cache.
Private Member Functions
void CheckCacheDirectoryExistence ()
Checks if the cache directory exists, and creates it if it does not.
async void Compress (byte[] bytes, string filePath)
Compresses a byte array using GZip and writes it to a file asynchronously.
byte[] Decompress (string fileName)
Decompresses a GZip file from the cache directory and returns its raw byte array.
string getCacheKey (int x, int y)
Generates a unique cache key string for a given tile coordinate.
string getFileNameByTile (int x, int y)
Gets the file name for a tile based on its coordinates.
Private Attributes
readonly object pendingCacheLock = new object()
Lock object to ensure thread-safe access to the pendingCacheLoad HashSet.
HashSet< string > pendingCacheLoad = new HashSet<string>()
A HashSet containing the file names of tiles that are currently being written to disk.
Detailed Description
Manages the disk-based caching of map tiles.
Tiles are compressed using GZip to save space and are stored in a platform-specific persistent data path. Includes thread-safe mechanisms to prevent reading a tile while it is being written.
Author: Eben, Ryan Version: 1.0
Definition at line 23 of file TileCacheManager.cs.
Member Function Documentation
CacheTileData()
void TileCacheManager.CacheTileData (Texture2D tileTexture, int x, int y)
Caches a tile texture to disk.
The texture is encoded to PNG and then compressed using GZip.
Parameters
tileTexture The Texture2D object of the tile.
x The tile X coordinate.
y The tile Y coordinate.
Definition at line 76 of file TileCacheManager.cs.
References Compress(), and getFileNameByTile().
checkAnyPendingLoad()
bool TileCacheManager.checkAnyPendingLoad (int x, int y)
Checks if a specific tile is currently being written to the cache.
Parameters
x The tile X coordinate.
y The tile Y coordinate.
Returns
True if the tile is being written, false otherwise.
Definition at line 62 of file TileCacheManager.cs.
References getFileNameByTile(), pendingCacheLoad, and pendingCacheLock.
CheckCacheDirectoryExistence()
void TileCacheManager.CheckCacheDirectoryExistence () private
Checks if the cache directory exists, and creates it if it does not.
Definition at line 115 of file TileCacheManager.cs.
References CachePath.
Referenced by ClearTileCache(), Compress(), and Decompress().
ClearTileCache()
void TileCacheManager.ClearTileCache ()
Clears the custom tile cache directory and Unity's built-in cache.
Definition at line 218 of file TileCacheManager.cs.
References CachePath, and CheckCacheDirectoryExistence().
Compress()
async void TileCacheManager.Compress (byte[] bytes, string filePath) private
Compresses a byte array using GZip and writes it to a file asynchronously.
Manages the pending cache load state for thread safety.
Parameters
bytes The raw byte data to compress (e.g., from Texture2D.EncodeToPNG()).
filePath The file name (not the full path) for the cache file.
Definition at line 130 of file TileCacheManager.cs.
References CachePath, CheckCacheDirectoryExistence(), pendingCacheLoad, and pendingCacheLock.
Referenced by CacheTileData().
Decompress()
byte[] TileCacheManager.Decompress (string fileName) private
Decompresses a GZip file from the cache directory and returns its raw byte array.
Parameters
fileName The file name (not the full path) to read from.
Returns
A byte array of the decompressed data, or null if the file doesn't exist or is being written.
Definition at line 163 of file TileCacheManager.cs.
References CachePath, CheckCacheDirectoryExistence(), and pendingCacheLoad.
Referenced by RetrieveCachedTile().
getCacheKey()
string TileCacheManager.getCacheKey (int x, int y) private
Generates a unique cache key string for a given tile coordinate.
Parameters
x The tile X coordinate.
y The tile Y coordinate.
Returns
A string key (e.g., "123_456").
Definition at line 199 of file TileCacheManager.cs.
Referenced by getFileNameByTile().
getFileNameByTile()
string TileCacheManager.getFileNameByTile (int x, int y) private
Gets the file name for a tile based on its coordinates.
Parameters
x The tile X coordinate.
y The tile Y coordinate.
Returns
The file name (e.g., "123_456").
Definition at line 210 of file TileCacheManager.cs.
References getCacheKey().
Referenced by CacheTileData(), checkAnyPendingLoad(), and RetrieveCachedTile().
RetrieveCachedTile()
async Task< Texture2D > TileCacheManager.RetrieveCachedTile (int x, int y)
Asynchronously retrieves a cached tile from the disk.
Parameters
x The tile X coordinate.
y The tile Y coordinate.
Returns
A Task that represents the asynchronous operation. The result is the loaded Texture2D if found, or null if a cache miss occurs.
Definition at line 92 of file TileCacheManager.cs.
References Decompress(), and getFileNameByTile().
Member Data Documentation
pendingCacheLoad
HashSet<string> TileCacheManager.pendingCacheLoad = new HashSet<string>() private
A HashSet containing the file names of tiles that are currently being written to disk.
This prevents attempts to read incomplete cache files.
Definition at line 54 of file TileCacheManager.cs.
Referenced by checkAnyPendingLoad(), Compress(), and Decompress().
pendingCacheLock
readonly object TileCacheManager.pendingCacheLock = new object() private
Lock object to ensure thread-safe access to the pendingCacheLoad HashSet.
Definition at line 48 of file TileCacheManager.cs.
Referenced by checkAnyPendingLoad(), and Compress().
Property Documentation
CachePath
string TileCacheManager.CachePath static get private
Gets the platform-specific root path for the tile cache.
Uses LocalApplicationData in the Editor and persistentDataPath in builds.
Definition at line 29 of file TileCacheManager.cs.
Referenced by CheckCacheDirectoryExistence(), ClearTileCache(), Compress(), and Decompress().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/TileCacheManager.cs