Idenguefy: Idenguefy.Controllers.EnvLoader Class Reference
Idenguefy.Controllers.EnvLoader Class Reference
A static utility class to load environment variables from a ".env" file at runtime.
Static Public Member Functions
static void Load (string path=".env")
Loads the specified .env file, parses its contents, and stores the key/value pairs in the internal dictionary.
static string Get (string key, string defaultValue="")
Safely retrieves a value from the loaded environment variables.
Static Private Attributes
static readonly Dictionary< string, string > envVars = new()
The private dictionary that stores the loaded key/value pairs.
Detailed Description
A static utility class to load environment variables from a ".env" file at runtime.
This allows for storing sensitive keys (like API keys) outside of source control.
Author: Napatr Version: 1.0 Note: Ensure a ".env" file is present in the project's root directory.
Definition at line 17 of file EnvLoader.cs.
Member Function Documentation
Get()
string Idenguefy.Controllers.EnvLoader.Get (string key, string defaultValue = "") static
Safely retrieves a value from the loaded environment variables.
Parameters
key The key (variable name) to retrieve.
defaultValue The value to return if the key is not found.
Returns
The stored value, or the default value if the key does not exist.
Definition at line 60 of file EnvLoader.cs.
References envVars.
Referenced by Idenguefy.Controllers.LocalizationManager.Awake(), Idenguefy.Controllers.MTSearchAPIHandler.Awake(), and Idenguefy.Controllers.MTTileAPIHandler.Awake().
Load()
void Idenguefy.Controllers.EnvLoader.Load (string path = ".env") static
Loads the specified .env file, parses its contents, and stores the key/value pairs in the internal dictionary.
Parameters
path The file path to the .env file. Defaults to ".env".
Definition at line 29 of file EnvLoader.cs.
References envVars.
Referenced by Idenguefy.Controllers.LocalizationManager.Awake(), Idenguefy.Controllers.MTSearchAPIHandler.Awake(), and Idenguefy.Controllers.MTTileAPIHandler.Awake().
Member Data Documentation
envVars
readonly Dictionary<string, string> Idenguefy.Controllers.EnvLoader.envVars = new() static private
The private dictionary that stores the loaded key/value pairs.
Definition at line 22 of file EnvLoader.cs.
Referenced by Get(), and Load().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/EnvLoader.cs