Idenguefy: Idenguefy.Controllers.MTSearchAPIHandler Class Reference
Idenguefy.Controllers.MTSearchAPIHandler Class Reference
The SearchAPIHandler implementation for MapTiler's Geocoding API.
Public Member Functions
override IEnumerator FetchSearchByQuery (string query)
Run the entire search flow: fetch raw data from API, preprocess into MapSearchResult list, assign to response.
IEnumerator FetchSearchByURL (string url, Action< string > onComplete)
To fetch raw Geocoding JSON data from MapTilerAPI given the constructed URL.
Public Member Functions inherited from Idenguefy.Controllers.SearchAPIHandler
void Start ()
IEnumerator FetchSearchByQuery (string query)
To search for locations based on user query.
Private Member Functions
void Awake ()
List< MapSearchResult > PreprocessSearchData (string json)
Parse raw JSON into list of MapSearchResult objects.
string getSearchURL (string query)
Construct.
Private Attributes
string key
Static Private Attributes
static readonly string base_url = "https://api.maptiler.com/geocoding/"
static readonly string country = "sg"
static readonly int limit = 5
Additional Inherited Members
Properties inherited from Idenguefy.Controllers.SearchAPIHandler
static SearchAPIResponse response [get, protected set]
Detailed Description
The SearchAPIHandler implementation for MapTiler's Geocoding API.
Responsibilities:
Request relevant GeocodingAPI location data based on the user's search query
Download the raw Geocoding dataset
Parse and convert features into MapSearchResult entities
Add preprocessed search results into an array
Wrap array with appropriate SearchAPIResponse Wrapper
Author: Eben Version: 1.0 Notes: N/A
Definition at line 30 of file MTSearchAPIHandler.cs.
Member Function Documentation
Awake()
void Idenguefy.Controllers.MTSearchAPIHandler.Awake () private
Definition at line 37 of file MTSearchAPIHandler.cs.
References Idenguefy.Controllers.EnvLoader.Get(), key, and Idenguefy.Controllers.EnvLoader.Load().
FetchSearchByQuery()
override IEnumerator Idenguefy.Controllers.MTSearchAPIHandler.FetchSearchByQuery (string query)
Run the entire search flow: fetch raw data from API, preprocess into MapSearchResult list, assign to response.
Parameters
query
Returns
Definition at line 50 of file MTSearchAPIHandler.cs.
References FetchSearchByURL(), getSearchURL(), and PreprocessSearchData().
FetchSearchByURL()
IEnumerator Idenguefy.Controllers.MTSearchAPIHandler.FetchSearchByURL (string url, Action< string > onComplete)
To fetch raw Geocoding JSON data from MapTilerAPI given the constructed URL.
Parameters
url The base URL of API
onComplete The action to pass in the onComplete method
Returns
Definition at line 84 of file MTSearchAPIHandler.cs.
Referenced by FetchSearchByQuery().
getSearchURL()
string Idenguefy.Controllers.MTSearchAPIHandler.getSearchURL (string query) private
Construct.
Parameters
query
Returns
Definition at line 138 of file MTSearchAPIHandler.cs.
Referenced by FetchSearchByQuery().
PreprocessSearchData()
List< MapSearchResult > Idenguefy.Controllers.MTSearchAPIHandler.PreprocessSearchData (string json) private
Parse raw JSON into list of MapSearchResult objects.
Parameters
json The json string to be parsed
Returns
Definition at line 104 of file MTSearchAPIHandler.cs.
Referenced by FetchSearchByQuery().
Member Data Documentation
base_url
readonly string Idenguefy.Controllers.MTSearchAPIHandler.base_url = "https://api.maptiler.com/geocoding/" static private
Definition at line 33 of file MTSearchAPIHandler.cs.
country
readonly string Idenguefy.Controllers.MTSearchAPIHandler.country = "sg" static private
Definition at line 35 of file MTSearchAPIHandler.cs.
key
string Idenguefy.Controllers.MTSearchAPIHandler.key private
Definition at line 34 of file MTSearchAPIHandler.cs.
Referenced by Awake().
limit
readonly int Idenguefy.Controllers.MTSearchAPIHandler.limit = 5 static private
Definition at line 36 of file MTSearchAPIHandler.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/API/MTSearchAPIHandler.cs