Idenguefy: Idenguefy.Controllers.MTTileAPIHandler Class Reference
Idenguefy.Controllers.MTTileAPIHandler Class Reference
The SearchAPIHandler implementation for MapTiler's Geocoding API.
Public Member Functions
override IEnumerator FetchMapTile (int x, int y, int zoom)
Run the entire tile-fetch flow: fetch taster map tiles from API, create a GameObject and assign texture.
Public Member Functions inherited from Idenguefy.Controllers.TileAPIHandler
void Start ()
IEnumerator FetchMapTile (int x, int y, int zoom)
To fetch the RASTER map tile 2D texture given the x, y, zoom parameters.
Private Member Functions
void Awake ()
IEnumerator FetchTileByURL (string url)
To fetch the RASTER map tile 2D texture given the x, y, zoom parameters via the constructed URL.
string constructURL (int x, int y, int zoom)
To construct the MapTiler API URL given the input parameter x, y, zoom parameters </smmary>
Parameters
x global y-coordinate of the tile
y global y-coordinate of the tile
zoom global zoom level of the map tile
Returns
.
Private Attributes
string API_KEY
Static Private Attributes
static readonly string BASE_URL = "https://api.maptiler.com/maps/"
static readonly string FORMAT = "png"
static readonly string STYLE_ID = "dataviz"
Additional Inherited Members
Properties inherited from Idenguefy.Controllers.TileAPIHandler
static TileAPIResponse response = new TileAPIResponse() [get, protected set]
Detailed Description
The SearchAPIHandler implementation for MapTiler's Geocoding API.
Responsibilities:
Request relevant tile (x, y, zoom) data to obtain texture data
Download the given raw 2d texture of the raster tiles
Parse and convert features into Texture2D entity
Wrap array with appropriate TileAPIResponse Wrapper
Author: Eben Version: 1.0 Notes: N/A
Definition at line 25 of file MTTileAPIHandler.cs.
Member Function Documentation
Awake()
void Idenguefy.Controllers.MTTileAPIHandler.Awake () private
Definition at line 32 of file MTTileAPIHandler.cs.
References API_KEY, Idenguefy.Controllers.EnvLoader.Get(), and Idenguefy.Controllers.EnvLoader.Load().
constructURL()
string Idenguefy.Controllers.MTTileAPIHandler.constructURL (int x, int y, int zoom) private
To construct the MapTiler API URL given the input parameter x, y, zoom parameters </smmary>
Parameters
x global y-coordinate of the tile
y global y-coordinate of the tile
zoom global zoom level of the map tile
Returns
.
Definition at line 92 of file MTTileAPIHandler.cs.
Referenced by FetchMapTile().
FetchMapTile()
override IEnumerator Idenguefy.Controllers.MTTileAPIHandler.FetchMapTile (int x, int y, int zoom)
Run the entire tile-fetch flow: fetch taster map tiles from API, create a GameObject and assign texture.
Parameters
query
Returns
Definition at line 47 of file MTTileAPIHandler.cs.
References constructURL(), and FetchTileByURL().
FetchTileByURL()
IEnumerator Idenguefy.Controllers.MTTileAPIHandler.FetchTileByURL (string url) private
To fetch the RASTER map tile 2D texture given the x, y, zoom parameters via the constructed URL.
Parameters
url
Returns
Definition at line 63 of file MTTileAPIHandler.cs.
Referenced by FetchMapTile().
Member Data Documentation
API_KEY
string Idenguefy.Controllers.MTTileAPIHandler.API_KEY private
Definition at line 28 of file MTTileAPIHandler.cs.
Referenced by Awake().
BASE_URL
readonly string Idenguefy.Controllers.MTTileAPIHandler.BASE_URL = "https://api.maptiler.com/maps/" static private
Definition at line 29 of file MTTileAPIHandler.cs.
FORMAT
readonly string Idenguefy.Controllers.MTTileAPIHandler.FORMAT = "png" static private
Definition at line 30 of file MTTileAPIHandler.cs.
STYLE_ID
readonly string Idenguefy.Controllers.MTTileAPIHandler.STYLE_ID = "dataviz" static private
Definition at line 31 of file MTTileAPIHandler.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/API/MTTileAPIHandler.cs