Idenguefy: Idenguefy.Controllers.ThemeManager Class Reference
Idenguefy.Controllers.ThemeManager Class Reference
Singleton manager for handling the application's visual theme.
Public Member Functions
void Register (ThemeApplier applier)
Registers a ThemeApplier to receive theme updates.
void Unregister (ThemeApplier applier)
Unregisters a ThemeApplier to stop it from receiving theme updates.
void ToggleTheme ()
Toggles the theme between light and dark mode and applies the new theme to all registered objects.
ThemeData GetCurrentTheme ()
Gets the ThemeData object for the currently active theme.
Public Attributes
ThemeData lightTheme
ThemeData darkTheme
Static Public Attributes
static ThemeManager Instance
The static singleton instance of the ThemeManager.
Private Member Functions
void Awake ()
Initializes the singleton pattern, ensuring only one ThemeManager exists and persists across scenes.
void ApplyThemeToAll ()
Iterates through all registered ThemeApplier objects and instructs them to apply the current theme.
Private Attributes
bool isDarkMode = false
readonly List< ThemeApplier > registeredObjects = new List<ThemeApplier>()
A private list of all ThemeApplier components that need to be updated when the theme changes.
Detailed Description
Singleton manager for handling the application's visual theme.
It allows toggling between light and dark modes and applies the selected theme to all registered UI elements via ThemeApplier.
Author: Napatr Version: 1.0 Notes: Ensures persistence across scenes.
Definition at line 18 of file ThemeManager.cs.
Member Function Documentation
ApplyThemeToAll()
void Idenguefy.Controllers.ThemeManager.ApplyThemeToAll () private
Iterates through all registered ThemeApplier objects and instructs them to apply the current theme.
Definition at line 148 of file ThemeManager.cs.
References GetCurrentTheme(), and registeredObjects.
Referenced by ToggleTheme().
Awake()
void Idenguefy.Controllers.ThemeManager.Awake () private
Initializes the singleton pattern, ensuring only one ThemeManager exists and persists across scenes.
Definition at line 84 of file ThemeManager.cs.
References Instance.
GetCurrentTheme()
ThemeData Idenguefy.Controllers.ThemeManager.GetCurrentTheme ()
Gets the ThemeData object for the currently active theme.
Returns
The ThemeData (light or dark) that is currently active.
Definition at line 139 of file ThemeManager.cs.
References darkTheme, isDarkMode, and lightTheme.
Referenced by ApplyThemeToAll(), and Register().
Register()
void Idenguefy.Controllers.ThemeManager.Register (ThemeApplier applier)
Registers a ThemeApplier to receive theme updates.
Immediately applies the current theme upon registration.
Parameters
applier The UI component to register.
Definition at line 104 of file ThemeManager.cs.
References Idenguefy.Boundaries.ThemeApplier.ApplyTheme(), GetCurrentTheme(), and registeredObjects.
Referenced by Idenguefy.Boundaries.ThemeApplier.OnEnable().
ToggleTheme()
void Idenguefy.Controllers.ThemeManager.ToggleTheme ()
Toggles the theme between light and dark mode and applies the new theme to all registered objects.
Definition at line 128 of file ThemeManager.cs.
References ApplyThemeToAll(), and isDarkMode.
Referenced by Idenguefy.Boundaries.ThemeApplier.OnToggleTheme().
Unregister()
void Idenguefy.Controllers.ThemeManager.Unregister (ThemeApplier applier)
Unregisters a ThemeApplier to stop it from receiving theme updates.
Parameters
applier The UI component to unregister.
Definition at line 117 of file ThemeManager.cs.
References registeredObjects.
Referenced by Idenguefy.Boundaries.ThemeApplier.OnDisable().
Member Data Documentation
darkTheme
ThemeData Idenguefy.Controllers.ThemeManager.darkTheme
Initial value:
= new ThemeData
        {
            backgroundColor = new Color(0.08f, 0.08f, 0.08f),
            textColor = Color.white,
            buttonColor = new Color(0.25f, 0.25f, 0.25f),
            buttonTextColor = Color.white,
            inputBackgroundColor = new Color(0.18f, 0.18f, 0.18f),
            inputTextColor = Color.white,
            placeholderTextColor = new Color(0.6f, 0.6f, 0.6f),
            sliderFillColor = new Color(0.7f, 0.7f, 0.7f),
            sliderBackgroundColor = new Color(0.3f, 0.3f, 0.3f),
            toggleOnColor = new Color(0.3f, 0.8f, 1f),
            toggleOffColor = new Color(0.3f, 0.3f, 0.3f),
            dropdownBackgroundColor = new Color(0.18f, 0.18f, 0.18f),
            dropdownTextColor = Color.white,
            dropdownArrowColor = new Color(0.8f, 0.8f, 0.8f),
            dropdownHighlightColor = new Color(0.3f, 0.3f, 0.3f)
        }
Definition at line 54 of file ThemeManager.cs.
Referenced by GetCurrentTheme().
Instance
ThemeManager Idenguefy.Controllers.ThemeManager.Instance static
The static singleton instance of the ThemeManager.
Definition at line 23 of file ThemeManager.cs.
Referenced by Awake(), Idenguefy.Boundaries.ThemeApplier.GetThemeDataFromMode(), Idenguefy.Boundaries.ThemeApplier.OnDisable(), Idenguefy.Boundaries.ThemeApplier.OnEnable(), and Idenguefy.Boundaries.ThemeApplier.OnToggleTheme().
isDarkMode
bool Idenguefy.Controllers.ThemeManager.isDarkMode = false private
Definition at line 27 of file ThemeManager.cs.
Referenced by GetCurrentTheme(), and ToggleTheme().
lightTheme
ThemeData Idenguefy.Controllers.ThemeManager.lightTheme
Initial value:
= new ThemeData
        {
            backgroundColor = new Color(0.9f, 0.9f, 0.9f),
            textColor = Color.black,
            buttonColor = new Color(0.75f, 0.75f, 0.75f),
            buttonTextColor = Color.black,
            inputBackgroundColor = new Color(0.95f, 0.95f, 0.95f),
            inputTextColor = Color.black,
            placeholderTextColor = new Color(0.4f, 0.4f, 0.4f),
            sliderFillColor = new Color(0.3f, 0.3f, 0.3f),
            sliderBackgroundColor = new Color(0.8f, 0.8f, 0.8f),
            toggleOnColor = new Color(0.2f, 0.6f, 1f),
            toggleOffColor = new Color(0.7f, 0.7f, 0.7f),
            dropdownBackgroundColor = new Color(0.95f, 0.95f, 0.95f),
            dropdownTextColor = Color.black,
            dropdownArrowColor = new Color(0.25f, 0.25f, 0.25f),
            dropdownHighlightColor = new Color(0.8f, 0.8f, 0.8f)
        }
Definition at line 31 of file ThemeManager.cs.
Referenced by GetCurrentTheme(), and Idenguefy.Boundaries.ThemeApplier.GetThemeDataFromMode().
registeredObjects
readonly List<ThemeApplier> Idenguefy.Controllers.ThemeManager.registeredObjects = new List<ThemeApplier>() private
A private list of all ThemeApplier components that need to be updated when the theme changes.
Definition at line 78 of file ThemeManager.cs.
Referenced by ApplyThemeToAll(), Register(), and Unregister().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/ThemeManager.cs