Idenguefy: Idenguefy.Controllers.LocalizationManager Class Reference
Idenguefy.Controllers.LocalizationManager Class Reference
Manages runtime text localization for the Idenguefy application.
Classes
class TranslationWrapper
class TranslationItem
class TranslationEntry
Public Member Functions
void Register (LocalizedText applier)
Registers a LocalizedText object to be managed by the LocalizationManager.
void Unregister (LocalizedText applier)
Unregisters a LocalizedText object from translation management.
void ToggleLanguage ()
Toggles between supported languages (English/Chinese).
string GetAPICode (string language)
Converts a human-readable language name to the corresponding API language code.
async Task< string > TranslateTextAsync (string sourceText, string targetLanguageCode)
Translates a source text string into the specified target language.
Public Attributes
string currentLanguageCode = "English"
The currently active language code (e.g., "English", "Chinese").
Static Public Attributes
static LocalizationManager Instance
Singleton instance of the LocalizationManager for global access.
Private Member Functions
void Awake ()
Initializes the LocalizationManager singleton and loads user language preferences.
async Task ApplyLanguageToAllAsync ()
Applies the currently selected language to all registered UI elements asynchronously, throttled to prevent hitting the translation API rate limit.
Private Attributes
string API_KEY
readonly List< LocalizedText > registeredObjects = new List<LocalizedText>()
List of all registered LocalizedText objects that require translation updates.
readonly Dictionary< string, string > translationCache = new Dictionary<string, string>()
Caches translated text to prevent redundant API calls for the same content.
Static Private Attributes
const int DelayBetweenRequestsMs = 100
Delay (in milliseconds) between sequential translation requests to prevent API rate limits.
const int MaxRetries = 3
Maximum number of retry attempts for HTTP 429 (Too Many Requests) responses.
Detailed Description
Manages runtime text localization for the Idenguefy application.
Responsibilities:
Registers UI elements and updates their language dynamically.
Communicates with Microsoft Translator API for translation.
Applies throttling, caching, and retry logic to prevent rate limits.
Persists the current language state globally across scenes.
Author: Napatr
Version: 1.0
This controller ensures consistent and efficient translation handling throughout the app.
Definition at line 25 of file LocalizationManager.cs.
Member Function Documentation
ApplyLanguageToAllAsync()
async Task Idenguefy.Controllers.LocalizationManager.ApplyLanguageToAllAsync () private
Applies the currently selected language to all registered UI elements asynchronously, throttled to prevent hitting the translation API rate limit.
Definition at line 121 of file LocalizationManager.cs.
References currentLanguageCode, DelayBetweenRequestsMs, and registeredObjects.
Referenced by ToggleLanguage().
Awake()
void Idenguefy.Controllers.LocalizationManager.Awake () private
Initializes the LocalizationManager singleton and loads user language preferences.
Definition at line 65 of file LocalizationManager.cs.
References API_KEY, currentLanguageCode, Idenguefy.Controllers.EnvLoader.Get(), Idenguefy.Controllers.SettingsController.GetLangPref(), Instance, and Idenguefy.Controllers.EnvLoader.Load().
GetAPICode()
string Idenguefy.Controllers.LocalizationManager.GetAPICode (string language)
Converts a human-readable language name to the corresponding API language code.
Parameters
language Display name (e.g., "English", "Chinese").
Returns
Language code used by the translation API (e.g., "en", "zh").
Definition at line 141 of file LocalizationManager.cs.
Referenced by Idenguefy.Boundaries.LocalizedText.ApplyCurrentLanguageToTextAsync(), and Idenguefy.Boundaries.LocalizedText.UpdateTextsAsync().
Register()
void Idenguefy.Controllers.LocalizationManager.Register (LocalizedText applier)
Registers a LocalizedText object to be managed by the LocalizationManager.
Automatically updates the text to the current language.
Parameters
applier The LocalizedText instance to register.
Definition at line 87 of file LocalizationManager.cs.
References currentLanguageCode, registeredObjects, and Idenguefy.Boundaries.LocalizedText.UpdateTextsAsync().
Referenced by Idenguefy.Boundaries.LocalizedText.OnEnable().
ToggleLanguage()
void Idenguefy.Controllers.LocalizationManager.ToggleLanguage ()
Toggles between supported languages (English/Chinese).
Reads the new preference from SettingsController and applies updates.
Definition at line 110 of file LocalizationManager.cs.
References ApplyLanguageToAllAsync(), currentLanguageCode, and Idenguefy.Controllers.SettingsController.GetLangPref().
Referenced by Idenguefy.Boundaries.LocalizedText.OnLanguageToggleButtonPressed().
TranslateTextAsync()
async Task< string > Idenguefy.Controllers.LocalizationManager.TranslateTextAsync (string sourceText, string targetLanguageCode)
Translates a source text string into the specified target language.
Uses the Microsoft Translator API with local caching, placeholder protection, and retry logic.
Parameters
sourceText The original text to translate.
targetLanguageCode The target language code (e.g., "en", "zh").
Returns
A task returning the translated text, or the original if translation fails.
Definition at line 158 of file LocalizationManager.cs.
References API_KEY, Idenguefy.Controllers.LocalizationManager.TranslationWrapper.items, MaxRetries, Idenguefy.Controllers.LocalizationManager.TranslationEntry.text, translationCache, and Idenguefy.Controllers.LocalizationManager.TranslationItem.translations.
Referenced by Idenguefy.Boundaries.LocalizedText.ApplyCurrentLanguageToTextAsync(), and Idenguefy.Boundaries.LocalizedText.UpdateTextsAsync().
Unregister()
void Idenguefy.Controllers.LocalizationManager.Unregister (LocalizedText applier)
Unregisters a LocalizedText object from translation management.
Parameters
applier The LocalizedText instance to remove.
Definition at line 100 of file LocalizationManager.cs.
References registeredObjects.
Referenced by Idenguefy.Boundaries.LocalizedText.OnDisable().
Member Data Documentation
API_KEY
string Idenguefy.Controllers.LocalizationManager.API_KEY private
Definition at line 27 of file LocalizationManager.cs.
Referenced by Awake(), and TranslateTextAsync().
currentLanguageCode
string Idenguefy.Controllers.LocalizationManager.currentLanguageCode = "English"
The currently active language code (e.g., "English", "Chinese").
Loaded from the user’s settings during initialization.
Definition at line 40 of file LocalizationManager.cs.
Referenced by Idenguefy.Boundaries.LocalizedText.ApplyCurrentLanguageToTextAsync(), ApplyLanguageToAllAsync(), Awake(), Register(), Idenguefy.Boundaries.LocalizedText.Start(), and ToggleLanguage().
DelayBetweenRequestsMs
const int Idenguefy.Controllers.LocalizationManager.DelayBetweenRequestsMs = 100 static private
Delay (in milliseconds) between sequential translation requests to prevent API rate limits.
Definition at line 55 of file LocalizationManager.cs.
Referenced by ApplyLanguageToAllAsync().
Instance
LocalizationManager Idenguefy.Controllers.LocalizationManager.Instance static
Singleton instance of the LocalizationManager for global access.
Definition at line 32 of file LocalizationManager.cs.
Referenced by Idenguefy.Boundaries.LocalizedText.ApplyCurrentLanguageToTextAsync(), Awake(), Idenguefy.Boundaries.LocalizedText.OnDisable(), Idenguefy.Boundaries.LocalizedText.OnEnable(), Idenguefy.Boundaries.LocalizedText.OnLanguageToggleButtonPressed(), Idenguefy.Boundaries.LocalizedText.Start(), and Idenguefy.Boundaries.LocalizedText.UpdateTextsAsync().
MaxRetries
const int Idenguefy.Controllers.LocalizationManager.MaxRetries = 3 static private
Maximum number of retry attempts for HTTP 429 (Too Many Requests) responses.
Definition at line 60 of file LocalizationManager.cs.
Referenced by TranslateTextAsync().
registeredObjects
readonly List<LocalizedText> Idenguefy.Controllers.LocalizationManager.registeredObjects = new List<LocalizedText>() private
List of all registered LocalizedText objects that require translation updates.
Definition at line 45 of file LocalizationManager.cs.
Referenced by ApplyLanguageToAllAsync(), Register(), and Unregister().
translationCache
readonly Dictionary<string, string> Idenguefy.Controllers.LocalizationManager.translationCache = new Dictionary<string, string>() private
Caches translated text to prevent redundant API calls for the same content.
Definition at line 50 of file LocalizationManager.cs.
Referenced by TranslateTextAsync().
The documentation for this class was generated from the following file:
Assets/Scripts/Controllers/LocalizationManager.cs