Idenguefy: Idenguefy.Boundaries.LocalizedText Class Reference
Idenguefy.Boundaries.LocalizedText Class Reference
Translates the language of relevant text fields selected within Unity's environment to a language selected from a list of options by the user.
Classes
class LocalizedEntry
Holds a reference to a TMP_Text component and its original, untranslated string.
Public Member Functions
async Task UpdateTextsAsync (string targetLanguage)
Asynchronously updates all registered text components to the target language.
void OnLanguageToggleButtonPressed ()
A public method intended to be used by a UI Button to trigger the language toggle in the LocalizationManager.
Private Member Functions
async void Start ()
Initializes the component by auto-populating text elements, applying the current language, and starting the watcher coroutine to detect runtime-instantiated text.
void OnEnable ()
Registers this component with the LocalizationManager when enabled.
void OnDisable ()
Unregisters this component from the LocalizationManager when disabled and stops the watcher coroutine.
void AutoPopulateTextElements ()
Finds all TMP_Text components in the scene (and children) and adds them to the localizedEntries list, skipping any marked with "IgnoreLocalisation".
System.Collections.IEnumerator WatchForNewTextElements ()
A coroutine that periodically scans for new TMP_Text elements that were instantiated at runtime and adds them to the localization list.
async Task ApplyCurrentLanguageToTextAsync (TMP_Text txt)
Applies the current language translation to a single, newly detected text component.
bool HasIgnoreParent (Transform t)
Checks if a transform or any of its ancestors have the "IgnoreLocalisation" tag.
Private Attributes
List< LocalizedEntry > localizedEntries = new List<LocalizedEntry>()
HashSet< TMP_Text > trackedTexts = new HashSet<TMP_Text>()
A HashSet for fast lookup to see if a text component is already being managed, to prevent duplicates.
bool isWatching = true
A flag to control the WatchForNewTextElements coroutine.
float scanInterval = 1f
The delay (in seconds) between scans for new, dynamically-added text elements.
Detailed Description
Translates the language of relevant text fields selected within Unity's environment to a language selected from a list of options by the user.
This component finds all TMP_Text objects and registers them for translation, skipping any with an "IgnoreLocalisation" tag. It also watches for new text elements added at runtime.
Author: Napatr Version: 1.0
Definition at line 19 of file LocalizedText.cs.
Member Function Documentation
ApplyCurrentLanguageToTextAsync()
async Task Idenguefy.Boundaries.LocalizedText.ApplyCurrentLanguageToTextAsync (TMP_Text txt) private
Applies the current language translation to a single, newly detected text component.
Parameters
txt The new text component to translate.
Returns
A Task representing the asynchronous translation operation.
Definition at line 187 of file LocalizedText.cs.
References Idenguefy.Controllers.LocalizationManager.currentLanguageCode, Idenguefy.Controllers.LocalizationManager.GetAPICode(), Idenguefy.Controllers.LocalizationManager.Instance, and Idenguefy.Controllers.LocalizationManager.TranslateTextAsync().
Referenced by WatchForNewTextElements().
AutoPopulateTextElements()
void Idenguefy.Boundaries.LocalizedText.AutoPopulateTextElements () private
Finds all TMP_Text components in the scene (and children) and adds them to the localizedEntries list, skipping any marked with "IgnoreLocalisation".
Definition at line 125 of file LocalizedText.cs.
References HasIgnoreParent(), localizedEntries, and trackedTexts.
Referenced by Start().
HasIgnoreParent()
bool Idenguefy.Boundaries.LocalizedText.HasIgnoreParent (Transform t) private
Checks if a transform or any of its ancestors have the "IgnoreLocalisation" tag.
Parameters
t The transform to start the check from.
Returns
True if an ignored parent is found, false otherwise.
Definition at line 213 of file LocalizedText.cs.
Referenced by AutoPopulateTextElements(), and WatchForNewTextElements().
OnDisable()
void Idenguefy.Boundaries.LocalizedText.OnDisable () private
Unregisters this component from the LocalizationManager when disabled and stops the watcher coroutine.
Definition at line 78 of file LocalizedText.cs.
References Idenguefy.Controllers.LocalizationManager.Instance, isWatching, and Idenguefy.Controllers.LocalizationManager.Unregister().
OnEnable()
void Idenguefy.Boundaries.LocalizedText.OnEnable () private
Registers this component with the LocalizationManager when enabled.
Definition at line 68 of file LocalizedText.cs.
References Idenguefy.Controllers.LocalizationManager.Instance, and Idenguefy.Controllers.LocalizationManager.Register().
OnLanguageToggleButtonPressed()
void Idenguefy.Boundaries.LocalizedText.OnLanguageToggleButtonPressed ()
A public method intended to be used by a UI Button to trigger the language toggle in the LocalizationManager.
Definition at line 202 of file LocalizedText.cs.
References Idenguefy.Controllers.LocalizationManager.Instance, and Idenguefy.Controllers.LocalizationManager.ToggleLanguage().
Start()
async void Idenguefy.Boundaries.LocalizedText.Start () private
Initializes the component by auto-populating text elements, applying the current language, and starting the watcher coroutine to detect runtime-instantiated text.
Definition at line 55 of file LocalizedText.cs.
References AutoPopulateTextElements(), Idenguefy.Controllers.LocalizationManager.currentLanguageCode, Idenguefy.Controllers.LocalizationManager.Instance, UpdateTextsAsync(), and WatchForNewTextElements().
UpdateTextsAsync()
async Task Idenguefy.Boundaries.LocalizedText.UpdateTextsAsync (string targetLanguage)
Asynchronously updates all registered text components to the target language.
Parameters
targetLanguage The display name of the target language (e.g., "English", "Chinese").
Returns
A Task representing the asynchronous translation operation.
Definition at line 91 of file LocalizedText.cs.
References Idenguefy.Controllers.LocalizationManager.GetAPICode(), Idenguefy.Controllers.LocalizationManager.Instance, localizedEntries, and Idenguefy.Controllers.LocalizationManager.TranslateTextAsync().
Referenced by Idenguefy.Controllers.LocalizationManager.Register(), and Start().
WatchForNewTextElements()
System.Collections.IEnumerator Idenguefy.Boundaries.LocalizedText.WatchForNewTextElements () private
A coroutine that periodically scans for new TMP_Text elements that were instantiated at runtime and adds them to the localization list.
Returns
An IEnumerator for the coroutine.
Definition at line 157 of file LocalizedText.cs.
References ApplyCurrentLanguageToTextAsync(), HasIgnoreParent(), isWatching, localizedEntries, scanInterval, and trackedTexts.
Referenced by Start().
Member Data Documentation
isWatching
bool Idenguefy.Boundaries.LocalizedText.isWatching = true private
A flag to control the WatchForNewTextElements coroutine.
Definition at line 45 of file LocalizedText.cs.
Referenced by OnDisable(), and WatchForNewTextElements().
localizedEntries
List<LocalizedEntry> Idenguefy.Boundaries.LocalizedText.localizedEntries = new List<LocalizedEntry>() private
Definition at line 36 of file LocalizedText.cs.
Referenced by AutoPopulateTextElements(), UpdateTextsAsync(), and WatchForNewTextElements().
scanInterval
float Idenguefy.Boundaries.LocalizedText.scanInterval = 1f private
The delay (in seconds) between scans for new, dynamically-added text elements.
Definition at line 49 of file LocalizedText.cs.
Referenced by WatchForNewTextElements().
trackedTexts
HashSet<TMP_Text> Idenguefy.Boundaries.LocalizedText.trackedTexts = new HashSet<TMP_Text>() private
A HashSet for fast lookup to see if a text component is already being managed, to prevent duplicates.
Definition at line 41 of file LocalizedText.cs.
Referenced by AutoPopulateTextElements(), and WatchForNewTextElements().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/LocalizedText.cs