Idenguefy: Idenguefy.Boundaries.SettingsView Class Reference
Idenguefy.Boundaries.SettingsView Class Reference
Displays the following adjustable fields to the user:
Proximity, adjustable through a slider
Language, interchangeable via a dropdown menu
Colour Theme, swapping between dark and light mode
Also includes an option to revert to default settings.
Public Member Functions
void ChangeMode (bool on)
Toggles between light and dark colour themes based on the toggle's state.
void DisplaySettings ()
Shows the settings menu.
void HideSettings ()
Hides the settings menu.
void ResetSettings ()
Resets all settings to their default values when triggered, updating it across the system.
Public Attributes
GameObject optionsBox
GameObject lightModeButton
GameObject darkModeButton
RectTransform lightModeUIHandle
Toggle toggle
Image backgroundImage
Color backgroundActiveColor
Color backgroundDefaultColor
TMP_Dropdown languageDropdown
Slider thresholdSlider
TMP_Text thresholdValueLabel
ThemeApplier themeApplier
PointerRenderer pointerRenderer
LocalizedText localizedText
Image backgroundPanel
TMP_Text[] textElements
Color lightBackground = Color.white
Color lightText = Color.black
Color darkBackground = new Color(0.1f, 0.1f, 0.1f)
Color darkText = Color.white
Private Member Functions
void Awake ()
Initializes the SettingsController.
void Start ()
Initializes all UI elements with values from the SettingsController and adds listeners for changes.
void ApplyTheme (Color bgColor, Color txtColor)
Sets the relevant elements to the specified light/dark colour mode based on the theme.
void OnLanguageChanged (int index)
Sets the language in the settings controller based on the users selected language and triggers the translation update.
void OnThresholdChanged (float value)
Updates the threshold value in the settings when the slider has been moved.
void UpdateThresholdLabel (int value)
Updates the value threshold label on the settings UI for the user to see.
Private Attributes
Vector2 handlePosition
Internal storage for the toggle's 'off' position.
SettingsController settingsController
An instance of the SettingsController to manage preference data.
Detailed Description
Displays the following adjustable fields to the user:
Proximity, adjustable through a slider
Language, interchangeable via a dropdown menu
Colour Theme, swapping between dark and light mode
Also includes an option to revert to default settings.
Author: Sharina, Xavier Version: 1.0
Definition at line 21 of file SettingsView.cs.
Member Function Documentation
ApplyTheme()
void Idenguefy.Boundaries.SettingsView.ApplyTheme (Color bgColor, Color txtColor) private
Sets the relevant elements to the specified light/dark colour mode based on the theme.
Parameters
bgColor The background color to apply.
txtColor The text color to apply.
Definition at line 172 of file SettingsView.cs.
References backgroundPanel, and textElements.
Referenced by ChangeMode().
Awake()
void Idenguefy.Boundaries.SettingsView.Awake () private
Initializes the SettingsController.
Definition at line 84 of file SettingsView.cs.
References settingsController.
ChangeMode()
void Idenguefy.Boundaries.SettingsView.ChangeMode (bool on)
Toggles between light and dark colour themes based on the toggle's state.
Parameters
on The state of the theme toggle (true for Dark Mode, false for Light Mode).
Definition at line 125 of file SettingsView.cs.
References ApplyTheme(), backgroundActiveColor, backgroundDefaultColor, darkBackground, darkText, handlePosition, lightBackground, lightText, pointerRenderer, settingsController, and themeApplier.
Referenced by ResetSettings(), and Start().
DisplaySettings()
void Idenguefy.Boundaries.SettingsView.DisplaySettings ()
Shows the settings menu.
Definition at line 151 of file SettingsView.cs.
References optionsBox, and thresholdSlider.
HideSettings()
void Idenguefy.Boundaries.SettingsView.HideSettings ()
Hides the settings menu.
Definition at line 160 of file SettingsView.cs.
References optionsBox, and thresholdSlider.
OnLanguageChanged()
void Idenguefy.Boundaries.SettingsView.OnLanguageChanged (int index) private
Sets the language in the settings controller based on the users selected language and triggers the translation update.
Parameters
index The index from the language dropdown (0=English, 1=Chinese).
Definition at line 189 of file SettingsView.cs.
References languageDropdown, localizedText, and settingsController.
Referenced by ResetSettings(), and Start().
OnThresholdChanged()
void Idenguefy.Boundaries.SettingsView.OnThresholdChanged (float value) private
Updates the threshold value in the settings when the slider has been moved.
Parameters
value The new value from the slider.
Definition at line 217 of file SettingsView.cs.
References settingsController, and UpdateThresholdLabel().
Referenced by Start().
ResetSettings()
void Idenguefy.Boundaries.SettingsView.ResetSettings ()
Resets all settings to their default values when triggered, updating it across the system.
The values to be reset, and their default values are:
Proximity Threshold = 500
Localisation = English
Light/Dark Mode = Light Mode
Definition at line 243 of file SettingsView.cs.
References ChangeMode(), handlePosition, languageDropdown, lightModeUIHandle, OnLanguageChanged(), settingsController, toggle, and UpdateThresholdLabel().
Start()
void Idenguefy.Boundaries.SettingsView.Start () private
Initializes all UI elements with values from the SettingsController and adds listeners for changes.
Definition at line 94 of file SettingsView.cs.
References ChangeMode(), handlePosition, languageDropdown, lightModeUIHandle, OnLanguageChanged(), OnThresholdChanged(), settingsController, thresholdSlider, toggle, and UpdateThresholdLabel().
UpdateThresholdLabel()
void Idenguefy.Boundaries.SettingsView.UpdateThresholdLabel (int value) private
Updates the value threshold label on the settings UI for the user to see.
Parameters
value The new threshold value to display.
Definition at line 228 of file SettingsView.cs.
References thresholdValueLabel.
Referenced by OnThresholdChanged(), ResetSettings(), and Start().
Member Data Documentation
backgroundActiveColor
Color Idenguefy.Boundaries.SettingsView.backgroundActiveColor
Definition at line 39 of file SettingsView.cs.
Referenced by ChangeMode().
backgroundDefaultColor
Color Idenguefy.Boundaries.SettingsView.backgroundDefaultColor
Definition at line 41 of file SettingsView.cs.
Referenced by ChangeMode().
backgroundImage
Image Idenguefy.Boundaries.SettingsView.backgroundImage
Definition at line 37 of file SettingsView.cs.
backgroundPanel
Image Idenguefy.Boundaries.SettingsView.backgroundPanel
Definition at line 67 of file SettingsView.cs.
Referenced by ApplyTheme().
darkBackground
Color Idenguefy.Boundaries.SettingsView.darkBackground = new Color(0.1f, 0.1f, 0.1f)
Definition at line 77 of file SettingsView.cs.
Referenced by ChangeMode().
darkModeButton
GameObject Idenguefy.Boundaries.SettingsView.darkModeButton
Definition at line 28 of file SettingsView.cs.
darkText
Color Idenguefy.Boundaries.SettingsView.darkText = Color.white
Definition at line 79 of file SettingsView.cs.
Referenced by ChangeMode().
handlePosition
Vector2 Idenguefy.Boundaries.SettingsView.handlePosition private
Internal storage for the toggle's 'off' position.
Definition at line 35 of file SettingsView.cs.
Referenced by ChangeMode(), ResetSettings(), and Start().
languageDropdown
TMP_Dropdown Idenguefy.Boundaries.SettingsView.languageDropdown
Definition at line 45 of file SettingsView.cs.
Referenced by OnLanguageChanged(), ResetSettings(), and Start().
lightBackground
Color Idenguefy.Boundaries.SettingsView.lightBackground = Color.white
Definition at line 72 of file SettingsView.cs.
Referenced by ChangeMode().
lightModeButton
GameObject Idenguefy.Boundaries.SettingsView.lightModeButton
Definition at line 26 of file SettingsView.cs.
lightModeUIHandle
RectTransform Idenguefy.Boundaries.SettingsView.lightModeUIHandle
Definition at line 31 of file SettingsView.cs.
Referenced by ResetSettings(), and Start().
lightText
Color Idenguefy.Boundaries.SettingsView.lightText = Color.black
Definition at line 74 of file SettingsView.cs.
Referenced by ChangeMode().
localizedText
LocalizedText Idenguefy.Boundaries.SettingsView.localizedText
Definition at line 63 of file SettingsView.cs.
Referenced by OnLanguageChanged().
optionsBox
GameObject Idenguefy.Boundaries.SettingsView.optionsBox
Definition at line 24 of file SettingsView.cs.
Referenced by DisplaySettings(), and HideSettings().
pointerRenderer
PointerRenderer Idenguefy.Boundaries.SettingsView.pointerRenderer
Definition at line 61 of file SettingsView.cs.
Referenced by ChangeMode().
settingsController
SettingsController Idenguefy.Boundaries.SettingsView.settingsController private
An instance of the SettingsController to manage preference data.
Definition at line 57 of file SettingsView.cs.
Referenced by Awake(), ChangeMode(), OnLanguageChanged(), OnThresholdChanged(), ResetSettings(), and Start().
textElements
TMP_Text [] Idenguefy.Boundaries.SettingsView.textElements
Definition at line 69 of file SettingsView.cs.
Referenced by ApplyTheme().
themeApplier
ThemeApplier Idenguefy.Boundaries.SettingsView.themeApplier
Definition at line 59 of file SettingsView.cs.
Referenced by ChangeMode().
thresholdSlider
Slider Idenguefy.Boundaries.SettingsView.thresholdSlider
Definition at line 52 of file SettingsView.cs.
Referenced by DisplaySettings(), HideSettings(), and Start().
thresholdValueLabel
TMP_Text Idenguefy.Boundaries.SettingsView.thresholdValueLabel
Definition at line 54 of file SettingsView.cs.
Referenced by UpdateThresholdLabel().
toggle
Toggle Idenguefy.Boundaries.SettingsView.toggle
Definition at line 33 of file SettingsView.cs.
Referenced by ResetSettings(), and Start().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/SettingsView.cs