Idenguefy: Idenguefy.Boundaries.InAppAlertService Class Reference
Idenguefy.Boundaries.InAppAlertService Class Reference
Displays the alerts detected in an InApp popup window The number of alerts that can be displayed in a window at once can be adjusted Includes options to view different preventative health tips based on the alert type (indoor/outdoor).
Public Member Functions
void OnAlertTriggered (AlertData data)
Callback method triggered by the AlertManager when a new alert is received.
void ClearAllInAppAlerts ()
Clearing the window of all in app alerts.
Public Attributes
RectTransform alertContainer
GameObject alertItemPrefab
PreventiveHealthTipsView healthTipsView
int maxVisibleAlerts = 10
Private Member Functions
void OnEnable ()
When enabled, starts a coroutine to register with the AlertManager.
System.Collections.IEnumerator EnsureRegistered ()
Coroutine that waits until the AlertManager instance is available, then registers this object as a subscriber.
void OnDisable ()
When disabled or destroyed, unregisters from the AlertManager to prevent null reference exceptions.
void EnforceMaxVisibleAlerts ()
Sets a limit on the number of alerts visible via the window at a given time.
Private Attributes
readonly List< GameObject > activeAlerts = new()
A list of the currently instantiated alert GameObjects in the view.
Detailed Description
Displays the alerts detected in an InApp popup window The number of alerts that can be displayed in a window at once can be adjusted Includes options to view different preventative health tips based on the alert type (indoor/outdoor).
Author: Xavier Version: 1.3
Definition at line 19 of file InAppAlertService.cs.
Member Function Documentation
ClearAllInAppAlerts()
void Idenguefy.Boundaries.InAppAlertService.ClearAllInAppAlerts ()
Clearing the window of all in app alerts.
Destroys all instantiated alert GameObjects.
Definition at line 144 of file InAppAlertService.cs.
References activeAlerts.
EnforceMaxVisibleAlerts()
void Idenguefy.Boundaries.InAppAlertService.EnforceMaxVisibleAlerts () private
Sets a limit on the number of alerts visible via the window at a given time.
Removes the oldest alerts if the count exceeds maxVisibleAlerts.
Definition at line 130 of file InAppAlertService.cs.
References activeAlerts, and maxVisibleAlerts.
Referenced by OnAlertTriggered().
EnsureRegistered()
System.Collections.IEnumerator Idenguefy.Boundaries.InAppAlertService.EnsureRegistered () private
Coroutine that waits until the AlertManager instance is available, then registers this object as a subscriber.
Definition at line 50 of file InAppAlertService.cs.
References Idenguefy.Controllers.AlertManager.Instance, and Idenguefy.Controllers.AlertManager.RegisterSubscriber().
Referenced by OnEnable().
OnAlertTriggered()
void Idenguefy.Boundaries.InAppAlertService.OnAlertTriggered (AlertData data)
Callback method triggered by the AlertManager when a new alert is received.
This method instantiates and populates a new alert item prefab.
Parameters
data The AlertData object containing information about the alert.
Implements Idenguefy.Controllers.IAlertSubscriber.
Definition at line 72 of file InAppAlertService.cs.
References activeAlerts, alertContainer, alertItemPrefab, EnforceMaxVisibleAlerts(), Idenguefy.Boundaries.AnimationManager.inAppAlertIsExpanded, Idenguefy.Boundaries.AnimationManager.Instance, Idenguefy.Boundaries.AnimationManager.ToggleInAppAlertView(), Idenguefy.Boundaries.AnimationManager.ToggleIndoorHealthTips(), and Idenguefy.Boundaries.AnimationManager.ToggleOutdoorHealthTips().
OnDisable()
void Idenguefy.Boundaries.InAppAlertService.OnDisable () private
When disabled or destroyed, unregisters from the AlertManager to prevent null reference exceptions.
Definition at line 61 of file InAppAlertService.cs.
References Idenguefy.Controllers.AlertManager.Instance, and Idenguefy.Controllers.AlertManager.UnregisterSubscriber().
OnEnable()
void Idenguefy.Boundaries.InAppAlertService.OnEnable () private
When enabled, starts a coroutine to register with the AlertManager.
Definition at line 41 of file InAppAlertService.cs.
References EnsureRegistered().
Member Data Documentation
activeAlerts
readonly List<GameObject> Idenguefy.Boundaries.InAppAlertService.activeAlerts = new() private
A list of the currently instantiated alert GameObjects in the view.
Definition at line 36 of file InAppAlertService.cs.
Referenced by ClearAllInAppAlerts(), EnforceMaxVisibleAlerts(), and OnAlertTriggered().
alertContainer
RectTransform Idenguefy.Boundaries.InAppAlertService.alertContainer
Definition at line 23 of file InAppAlertService.cs.
Referenced by OnAlertTriggered().
alertItemPrefab
GameObject Idenguefy.Boundaries.InAppAlertService.alertItemPrefab
Definition at line 25 of file InAppAlertService.cs.
Referenced by OnAlertTriggered().
healthTipsView
PreventiveHealthTipsView Idenguefy.Boundaries.InAppAlertService.healthTipsView
Definition at line 27 of file InAppAlertService.cs.
maxVisibleAlerts
int Idenguefy.Boundaries.InAppAlertService.maxVisibleAlerts = 10
Definition at line 31 of file InAppAlertService.cs.
Referenced by EnforceMaxVisibleAlerts().
The documentation for this class was generated from the following file:
Assets/Scripts/Boundaries/InAppAlertService.cs